
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-09T13:00:55-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "19b597689b15cab4fe5192293009fa63f5b7e2d2",
 "version": "1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
