# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from spaceone.api.inventory.v1 import zone_pb2 as spaceone_dot_api_dot_inventory_dot_v1_dot_zone__pb2


class ZoneStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.create = channel.unary_unary(
        '/spaceone.api.inventory.v1.Zone/create',
        request_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_zone__pb2.CreateZoneRequest.SerializeToString,
        response_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_zone__pb2.ZoneInfo.FromString,
        )
    self.update = channel.unary_unary(
        '/spaceone.api.inventory.v1.Zone/update',
        request_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_zone__pb2.UpdateZoneRequest.SerializeToString,
        response_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_zone__pb2.ZoneInfo.FromString,
        )
    self.delete = channel.unary_unary(
        '/spaceone.api.inventory.v1.Zone/delete',
        request_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_zone__pb2.ZoneRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.get = channel.unary_unary(
        '/spaceone.api.inventory.v1.Zone/get',
        request_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_zone__pb2.ZoneRequest.SerializeToString,
        response_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_zone__pb2.ZoneInfo.FromString,
        )
    self.add_member = channel.unary_unary(
        '/spaceone.api.inventory.v1.Zone/add_member',
        request_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_zone__pb2.ZoneMemberRequest.SerializeToString,
        response_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_zone__pb2.ZoneMemberInfo.FromString,
        )
    self.modify_member = channel.unary_unary(
        '/spaceone.api.inventory.v1.Zone/modify_member',
        request_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_zone__pb2.ZoneMemberRequest.SerializeToString,
        response_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_zone__pb2.ZoneMemberInfo.FromString,
        )
    self.remove_member = channel.unary_unary(
        '/spaceone.api.inventory.v1.Zone/remove_member',
        request_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_zone__pb2.RemoveZoneMemberRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.list_members = channel.unary_unary(
        '/spaceone.api.inventory.v1.Zone/list_members',
        request_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_zone__pb2.ZoneMemberQuery.SerializeToString,
        response_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_zone__pb2.ZoneMembersInfo.FromString,
        )
    self.list = channel.unary_unary(
        '/spaceone.api.inventory.v1.Zone/list',
        request_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_zone__pb2.ZoneQuery.SerializeToString,
        response_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_zone__pb2.ZonesInfo.FromString,
        )


class ZoneServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def create(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def update(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def add_member(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def modify_member(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def remove_member(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def list_members(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def list(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ZoneServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'create': grpc.unary_unary_rpc_method_handler(
          servicer.create,
          request_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_zone__pb2.CreateZoneRequest.FromString,
          response_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_zone__pb2.ZoneInfo.SerializeToString,
      ),
      'update': grpc.unary_unary_rpc_method_handler(
          servicer.update,
          request_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_zone__pb2.UpdateZoneRequest.FromString,
          response_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_zone__pb2.ZoneInfo.SerializeToString,
      ),
      'delete': grpc.unary_unary_rpc_method_handler(
          servicer.delete,
          request_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_zone__pb2.ZoneRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'get': grpc.unary_unary_rpc_method_handler(
          servicer.get,
          request_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_zone__pb2.ZoneRequest.FromString,
          response_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_zone__pb2.ZoneInfo.SerializeToString,
      ),
      'add_member': grpc.unary_unary_rpc_method_handler(
          servicer.add_member,
          request_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_zone__pb2.ZoneMemberRequest.FromString,
          response_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_zone__pb2.ZoneMemberInfo.SerializeToString,
      ),
      'modify_member': grpc.unary_unary_rpc_method_handler(
          servicer.modify_member,
          request_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_zone__pb2.ZoneMemberRequest.FromString,
          response_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_zone__pb2.ZoneMemberInfo.SerializeToString,
      ),
      'remove_member': grpc.unary_unary_rpc_method_handler(
          servicer.remove_member,
          request_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_zone__pb2.RemoveZoneMemberRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'list_members': grpc.unary_unary_rpc_method_handler(
          servicer.list_members,
          request_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_zone__pb2.ZoneMemberQuery.FromString,
          response_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_zone__pb2.ZoneMembersInfo.SerializeToString,
      ),
      'list': grpc.unary_unary_rpc_method_handler(
          servicer.list,
          request_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_zone__pb2.ZoneQuery.FromString,
          response_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_zone__pb2.ZonesInfo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'spaceone.api.inventory.v1.Zone', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
