
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-11T20:25:15-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "b91a3d51c538620a22559bf02ccd31a124a841fd",
 "version": "0.7.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
