
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-05T10:45:22-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ab4070b0ea81ef31841160b4e48de13d8cef3937",
 "version": "5.0b10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
