
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-09T10:14:36+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "14833cc2cd1bcf5cfcda0e99b4b9670ce73fd6f2",
 "version": "0.7.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
