
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-06T20:22:02-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "b9f40e58f44e68f026600332d139e8fdc66a28a4",
 "version": "0.7.5.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
