
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-02T14:52:43+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "667b57b89fff5eb41fc84c82ecf990275442753b",
 "version": "0.0.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
