[tool.poetry]
name = "trajpandas"
version = "0.3.0"
description = ""
authors = ["Bror Jonsson <brorfred@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.7"
pandas = "^1"
numpy = "^1"
scipy = "^1"

[tool.poetry.dev-dependencies]
pytest = "^3"
netCDF4 = "^1.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
