
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-07T09:49:24-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "2301651eac981493e7aa11ddc1eed21c35bcd885",
 "version": "v0.1.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
