
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-05T09:54:52-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "180e735c79ee5861f14abd22baa6076c413db225",
 "version": "5.0b6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
