
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-07T12:08:56+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "412b61844afa8420c52ea2fd2a1a9008f7091d29",
 "version": "0.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
