
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-05T11:00:33-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "0e733156b8f1d449e9fc9165916c608f9ec5f988",
 "version": "5.0b13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
