[tool.poetry]
name = "sqlwrap"
version = "0.0.1"
description = "Easy wrapper for various SQL libraries"
authors = ["mitch3x3 <mitch3x3@github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
psycopg2-binary = "^2.8.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
