# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from spaceone.api.monitoring import data_source_pb2 as spaceone_dot_api_dot_monitoring_dot_data__source__pb2


class DataSourceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.create = channel.unary_unary(
        '/spaceone.api.monitoring.v1.DataSource/create',
        request_serializer=spaceone_dot_api_dot_monitoring_dot_data__source__pb2.RegisterDataSourceRequest.SerializeToString,
        response_deserializer=spaceone_dot_api_dot_monitoring_dot_data__source__pb2.DataSourceInfo.FromString,
        )
    self.update = channel.unary_unary(
        '/spaceone.api.monitoring.v1.DataSource/update',
        request_serializer=spaceone_dot_api_dot_monitoring_dot_data__source__pb2.UpdateDataSourceRequest.SerializeToString,
        response_deserializer=spaceone_dot_api_dot_monitoring_dot_data__source__pb2.DataSourceInfo.FromString,
        )
    self.enable = channel.unary_unary(
        '/spaceone.api.monitoring.v1.DataSource/enable',
        request_serializer=spaceone_dot_api_dot_monitoring_dot_data__source__pb2.DataSourceRequest.SerializeToString,
        response_deserializer=spaceone_dot_api_dot_monitoring_dot_data__source__pb2.DataSourceInfo.FromString,
        )
    self.disable = channel.unary_unary(
        '/spaceone.api.monitoring.v1.DataSource/disable',
        request_serializer=spaceone_dot_api_dot_monitoring_dot_data__source__pb2.DataSourceRequest.SerializeToString,
        response_deserializer=spaceone_dot_api_dot_monitoring_dot_data__source__pb2.DataSourceInfo.FromString,
        )
    self.delete = channel.unary_unary(
        '/spaceone.api.monitoring.v1.DataSource/delete',
        request_serializer=spaceone_dot_api_dot_monitoring_dot_data__source__pb2.DataSourceRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.verify_plugin = channel.unary_unary(
        '/spaceone.api.monitoring.v1.DataSource/verify_plugin',
        request_serializer=spaceone_dot_api_dot_monitoring_dot_data__source__pb2.VerifyPluginRequest.SerializeToString,
        response_deserializer=spaceone_dot_api_dot_monitoring_dot_data__source__pb2.VerifyInfo.FromString,
        )
    self.get = channel.unary_unary(
        '/spaceone.api.monitoring.v1.DataSource/get',
        request_serializer=spaceone_dot_api_dot_monitoring_dot_data__source__pb2.DataSourceRequest.SerializeToString,
        response_deserializer=spaceone_dot_api_dot_monitoring_dot_data__source__pb2.DataSourceInfo.FromString,
        )
    self.list = channel.unary_unary(
        '/spaceone.api.monitoring.v1.DataSource/list',
        request_serializer=spaceone_dot_api_dot_monitoring_dot_data__source__pb2.DataSourceQuery.SerializeToString,
        response_deserializer=spaceone_dot_api_dot_monitoring_dot_data__source__pb2.DataSourcesInfo.FromString,
        )


class DataSourceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def create(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def update(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def enable(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def disable(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def verify_plugin(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def list(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DataSourceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'create': grpc.unary_unary_rpc_method_handler(
          servicer.create,
          request_deserializer=spaceone_dot_api_dot_monitoring_dot_data__source__pb2.RegisterDataSourceRequest.FromString,
          response_serializer=spaceone_dot_api_dot_monitoring_dot_data__source__pb2.DataSourceInfo.SerializeToString,
      ),
      'update': grpc.unary_unary_rpc_method_handler(
          servicer.update,
          request_deserializer=spaceone_dot_api_dot_monitoring_dot_data__source__pb2.UpdateDataSourceRequest.FromString,
          response_serializer=spaceone_dot_api_dot_monitoring_dot_data__source__pb2.DataSourceInfo.SerializeToString,
      ),
      'enable': grpc.unary_unary_rpc_method_handler(
          servicer.enable,
          request_deserializer=spaceone_dot_api_dot_monitoring_dot_data__source__pb2.DataSourceRequest.FromString,
          response_serializer=spaceone_dot_api_dot_monitoring_dot_data__source__pb2.DataSourceInfo.SerializeToString,
      ),
      'disable': grpc.unary_unary_rpc_method_handler(
          servicer.disable,
          request_deserializer=spaceone_dot_api_dot_monitoring_dot_data__source__pb2.DataSourceRequest.FromString,
          response_serializer=spaceone_dot_api_dot_monitoring_dot_data__source__pb2.DataSourceInfo.SerializeToString,
      ),
      'delete': grpc.unary_unary_rpc_method_handler(
          servicer.delete,
          request_deserializer=spaceone_dot_api_dot_monitoring_dot_data__source__pb2.DataSourceRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'verify_plugin': grpc.unary_unary_rpc_method_handler(
          servicer.verify_plugin,
          request_deserializer=spaceone_dot_api_dot_monitoring_dot_data__source__pb2.VerifyPluginRequest.FromString,
          response_serializer=spaceone_dot_api_dot_monitoring_dot_data__source__pb2.VerifyInfo.SerializeToString,
      ),
      'get': grpc.unary_unary_rpc_method_handler(
          servicer.get,
          request_deserializer=spaceone_dot_api_dot_monitoring_dot_data__source__pb2.DataSourceRequest.FromString,
          response_serializer=spaceone_dot_api_dot_monitoring_dot_data__source__pb2.DataSourceInfo.SerializeToString,
      ),
      'list': grpc.unary_unary_rpc_method_handler(
          servicer.list,
          request_deserializer=spaceone_dot_api_dot_monitoring_dot_data__source__pb2.DataSourceQuery.FromString,
          response_serializer=spaceone_dot_api_dot_monitoring_dot_data__source__pb2.DataSourcesInfo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'spaceone.api.monitoring.v1.DataSource', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
