#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['named_dataframes']

package_data = \
{'': ['*']}

install_requires = \
['pandas >= 0.25']

setup(name='named_dataframes',
      version='0.1.3',
      description='DataFrames with names.',
      author='Bao Wei',
      author_email='baowei.ur521@gmail.com',
      url=None,
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
     )
