# This file was automatically generated by sub\epyqlib\epyqlib\cli\generateversion.py
__version_build_time__ = '2020-04-13T18:28:45.815100'

__version__ = '2020.4.5'
__sha__ = '812ece73ae29c4fa43288598b3669f33c60d4e0f'
__revision__ = '812ece73ae29c4fa43288598b3669f33c60d4e0f'
