
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-10T13:12:52-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e8b26c827049bf8240e15d83105f7ebbfeb2d5c2",
 "version": "3.16.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
