
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-10T10:12:17-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "5fa2dbd670c053177086ecb7027f361e2c070e29",
 "version": "0.9.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
