name: Windows

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.python-version }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7"]

    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Show conda info
        run: |
          conda info
          conda list
      - name: Install dependencies
        run: |
          conda install --yes --quiet numpy scipy mkl-service libpython m2w64-toolchain astropy matplotlib theano
          conda install --yes --quiet -c conda-forge pybind11 celerite
          python -m pip install -U pip pytest-astropy
          python -m pip install -r requirements-test.txt
          python -m pip install -e .
      - name: Test with pytest
        run: |
          python -m pytest -vs src/exoplanet

#       - name: Set up Python 3.8
#         uses: actions/setup-python@v1
#         with:
#           python-version: 3.8
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           python -m pip install .
#       - name: Lint with black and mypy
#         run: |
#           python -m pip install black mypy
#           black --check src
#           mypy --ignore-missing-imports src
#       - name: Test with pytest
#         run: |
#           python -m pip install pytest pytest-aiohttp
#           python -m pytest -vs tests
