dist: bionic
sudo: required
language: python
matrix:
  include:
    - python: 3.7
      env: TOXENV=py37
    - python: 3.6_with_system_site_packages
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=check

before_install:
  - sudo apt-get update
  - sudo apt-get install -qq net-tools python3 udhcpd python-gst-1.0 python3-gi gir1.2-gtk-3.0
  - sudo apt-get install -qq gir1.2-gstreamer-1.0 gir1.2-gst-plugins-base-1.0 gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly
  - sudo apt-get install -qq gcc libgirepository1.0-dev libgtk-3-dev pkg-config

install:
  - pip install tox-travis coveralls pep517

script: tox

after_success:
  - python -m pep517.build .
  - coveralls

deploy:
  - provider: pypi
    user: __token__
    password:
      secure: "dzHgiwB0mmOfFn0M/XkoYyb/YME1EN2TWCqJB/PtQl/gc/koAQJlbtC3hVbXvuIGshgLA2O9gdqmGOZXLTv9LweUKIw6Q3wNQJzGYrj1+ADjdmmh4lD2ivBu8TYaBHvy730Pzwzbos31dFLMFO44SUkFDOwLb0UGMwDDmS6q5QgR10kFZeg76pNW6z/yUOH73c0wN2xzZgnCRSdG5JGbmTpnoUiBBRWFp7WQLONVPI55ckHdl7dilO0iEc8nzXi76uUlNsS4Ghrb4PpBRrtHHxl5FgrEgl5AjF7AWd3VNS965K0pIfqC4AXlryhGL9v0B4h/0wpb0wz1JZ8Rpd4/RN23uFzcw7oDqwu0kykcsQHyP3QxTmr5RjEM3YGII0mNqL6WEBQQykyiV9OleDHwqKIcoCYuf1Vd2naxOaeDDkCvVZweyiZm8WXNgCaQ2MZD30qjBC/fjav2ekY/3HQkBs5RQch1NlbahMdx+nyRpX4T7swZjvlPrDjOZCsgrry5RmYg6v79uHbdznEAQDv9qUjxOkdlCcvRm4H+269DQqESBKg4/iRye3rw6wh+D9rNc5wp8qYyu+UAFQcK1Pddpu5TUCyu9qqovqLdMKFvJvzuiBt9el+qPZPglLojx9AwwN1ejmvwuKfrtOIOkWsAIFme/ZSWJmBLeAAxmYb3ViE="
    file_glob: true
    file:
    - dist/*.whl
    skip_cleanup: true
    skip_existing: true
    on:
      repo: miurahr/picast
      tags: true
