[tool.isort]
force_single_line = true
import_heading_firstparty = "betanin"
import_heading_stdlib = "standard library"
import_heading_thirdparty = "3rd party"
known_first_party = "betanin"
length_sort = true
lines_after_imports = 2
multi_line_output = 3
sections = "STDLIB,THIRDPARTY,FIRSTPARTY"

[tool.black]
line-length = 79
target_version = ['py37']
