services:
  - docker

stages:
  - test
  - name: publish
    if: tag IS present

jobs:
  include:
    - stage: test
      language: python
      python:
        - "3.8"
      before_install:
        - pip install --upgrade pip
      install:
        - pip install codecov
      script:
        - make test
      after_success:
        - codecov
    - stage: publish
      language: generic
      deploy:
        provider: script
        script: make docker/publish
        on:
          all_branches: true
