# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from spaceone.api.inventory.v1 import subnet_pb2 as spaceone_dot_api_dot_inventory_dot_v1_dot_subnet__pb2


class SubnetStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.create = channel.unary_unary(
        '/spaceone.api.inventory.v1.Subnet/create',
        request_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_subnet__pb2.CreateSubnetRequest.SerializeToString,
        response_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_subnet__pb2.SubnetInfo.FromString,
        )
    self.update = channel.unary_unary(
        '/spaceone.api.inventory.v1.Subnet/update',
        request_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_subnet__pb2.UpdateSubnetRequest.SerializeToString,
        response_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_subnet__pb2.SubnetInfo.FromString,
        )
    self.pin_data = channel.unary_unary(
        '/spaceone.api.inventory.v1.Subnet/pin_data',
        request_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_subnet__pb2.PinSubnetDataRequest.SerializeToString,
        response_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_subnet__pb2.SubnetInfo.FromString,
        )
    self.delete = channel.unary_unary(
        '/spaceone.api.inventory.v1.Subnet/delete',
        request_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_subnet__pb2.SubnetRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.get = channel.unary_unary(
        '/spaceone.api.inventory.v1.Subnet/get',
        request_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_subnet__pb2.SubnetRequest.SerializeToString,
        response_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_subnet__pb2.SubnetInfo.FromString,
        )
    self.list = channel.unary_unary(
        '/spaceone.api.inventory.v1.Subnet/list',
        request_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_subnet__pb2.SubnetQuery.SerializeToString,
        response_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_subnet__pb2.SubnetsInfo.FromString,
        )


class SubnetServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def create(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def update(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def pin_data(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def list(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SubnetServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'create': grpc.unary_unary_rpc_method_handler(
          servicer.create,
          request_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_subnet__pb2.CreateSubnetRequest.FromString,
          response_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_subnet__pb2.SubnetInfo.SerializeToString,
      ),
      'update': grpc.unary_unary_rpc_method_handler(
          servicer.update,
          request_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_subnet__pb2.UpdateSubnetRequest.FromString,
          response_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_subnet__pb2.SubnetInfo.SerializeToString,
      ),
      'pin_data': grpc.unary_unary_rpc_method_handler(
          servicer.pin_data,
          request_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_subnet__pb2.PinSubnetDataRequest.FromString,
          response_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_subnet__pb2.SubnetInfo.SerializeToString,
      ),
      'delete': grpc.unary_unary_rpc_method_handler(
          servicer.delete,
          request_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_subnet__pb2.SubnetRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'get': grpc.unary_unary_rpc_method_handler(
          servicer.get,
          request_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_subnet__pb2.SubnetRequest.FromString,
          response_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_subnet__pb2.SubnetInfo.SerializeToString,
      ),
      'list': grpc.unary_unary_rpc_method_handler(
          servicer.list,
          request_deserializer=spaceone_dot_api_dot_inventory_dot_v1_dot_subnet__pb2.SubnetQuery.FromString,
          response_serializer=spaceone_dot_api_dot_inventory_dot_v1_dot_subnet__pb2.SubnetsInfo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'spaceone.api.inventory.v1.Subnet', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
