# coding: utf-8

"""
    VeeRoute.LSS Merchandiser

    Программный интерфейс для планирования работ торговых предствителей.  # noqa: E501

    OpenAPI spec version: 2.5.156470
    Contact: support@veeroute.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "vrt_lss_merchandiser"
VERSION = "2.5.156470"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="VeeRoute.LSS Merchandiser",
    author_email="support@veeroute.com",
    url="https://docs.veeroute.com/#/lss/merchandiser",
    keywords=["Swagger", "VeeRoute.LSS Merchandiser"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    Программный интерфейс для планирования работ торговых предствителей.  # noqa: E501
    """
)
