
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-12T16:13:19-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "6931e56f845b3d79de33760dc4c04532dc36a14d",
 "version": "2020.4.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
