# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DashboardCopy(Model):
    """DashboardCopy.

    :param dashboard_info: The Dashboard Title <span
     class='property-internal'>Must be between 0 and 255 characters</span>
    :type dashboard_info: str
    :param description: The dashboard description <span
     class='property-internal'>Must be between 0 and 255 characters</span>
    :type description: str
    :param shared: Flag to indicate if the dashboard is shared
    :type shared: bool
    :param public: Flag to indicate if the dashboard is public
    :type public: bool
    """

    _validation = {
        'dashboard_info': {'max_length': 255, 'min_length': 0},
        'description': {'max_length': 255, 'min_length': 0},
    }

    _attribute_map = {
        'dashboard_info': {'key': 'dashboardInfo', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
        'shared': {'key': 'shared', 'type': 'bool'},
        'public': {'key': 'public', 'type': 'bool'},
    }

    def __init__(self, dashboard_info=None, description=None, shared=None, public=None):
        super(DashboardCopy, self).__init__()
        self.dashboard_info = dashboard_info
        self.description = description
        self.shared = shared
        self.public = public
