# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ObservationTypeChild(Model):
    """ObservationTypeChild.

    :param observation_type_id: The observation type identifier
    :type observation_type_id: int
    :param observation_type_code: The observation type code
    :type observation_type_code: str
    :param observation_type_info: The observation type info
    :type observation_type_info: str
    :param noun_id: The identifier for the observation type's noun
    :type noun_id: int
    :param noun_code: The observation type's noun code
    :type noun_code: str
    :param credit: Indicates the type of credit for the observation type.
     Possible values include: 1 (Credit), 2 (Debit), 3 (Ignore)
    :type credit: int
    """

    _attribute_map = {
        'observation_type_id': {'key': 'observationTypeId', 'type': 'int'},
        'observation_type_code': {'key': 'observationTypeCode', 'type': 'str'},
        'observation_type_info': {'key': 'observationTypeInfo', 'type': 'str'},
        'noun_id': {'key': 'nounId', 'type': 'int'},
        'noun_code': {'key': 'nounCode', 'type': 'str'},
        'credit': {'key': 'credit', 'type': 'int'},
    }

    def __init__(self, observation_type_id=None, observation_type_code=None, observation_type_info=None, noun_id=None, noun_code=None, credit=None):
        super(ObservationTypeChild, self).__init__()
        self.observation_type_id = observation_type_id
        self.observation_type_code = observation_type_code
        self.observation_type_info = observation_type_info
        self.noun_id = noun_id
        self.noun_code = noun_code
        self.credit = credit
