
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-05T13:00:10-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "498bdf93bb8417e977c9874c2f69371971027951",
 "version": "2.2.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
