
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-09T12:47:26+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "09ad1a485a5badb855b0e613c21f5eeab855ba5b",
 "version": "0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
