
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-03T04:05:13+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "03c91fd4f1b981edea3d6f8304c024eb8944cf32",
 "version": "1.4.0.post.dev95"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
