
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-14T09:01:46+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "668802b7ba7c9b6ea559b5b4292b3d070430beae",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
