# Generated by Django 2.2.11 on 2020-03-21 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_power_cms', '0016_auto_20200321_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topbarwidget',
            name='brand_link',
        ),
        migrations.RemoveField(
            model_name='topbarwidget',
            name='brand_link_target',
        ),
    ]
