# Generated by Django 2.2.11 on 2020-03-22 14:36

from django.db import migrations, models
import django.db.models.deletion
import django_power_cms.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_power_cms', '0019_auto_20200322_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagewidget',
            name='widget',
            field=models.ForeignKey(limit_choices_to=django_power_cms.models.limit_choices_to_selected_site, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='django_power_cms.Widget', verbose_name='Widget'),
        ),
    ]
