# Generated by Django 2.2.11 on 2020-03-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_power_cms', '0021_cardsitem_cardswidget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardswidget',
            name='height',
        ),
        migrations.RemoveField(
            model_name='cardswidget',
            name='width',
        ),
        migrations.AddField(
            model_name='cardswidget',
            name='card_height',
            field=models.CharField(default='128px', max_length=32, verbose_name='Card Height'),
        ),
        migrations.AddField(
            model_name='cardswidget',
            name='card_width',
            field=models.CharField(default='80px', max_length=32, verbose_name='Card Width'),
        ),
        migrations.AddField(
            model_name='cardswidget',
            name='image_height',
            field=models.CharField(default='128px', max_length=32, verbose_name='Image Height'),
        ),
        migrations.AddField(
            model_name='cardswidget',
            name='image_width',
            field=models.CharField(default='120px', max_length=32, verbose_name='Image Width'),
        ),
    ]
