# Generated by Django 2.2.11 on 2020-03-23 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_power_cms', '0022_auto_20200323_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardswidget',
            name='title_height',
            field=models.CharField(default='30px', max_length=32, verbose_name='Title Height'),
        ),
        migrations.AlterField(
            model_name='cardswidget',
            name='card_height',
            field=models.CharField(default='120px', max_length=32, verbose_name='Card Height'),
        ),
        migrations.AlterField(
            model_name='cardswidget',
            name='card_width',
            field=models.CharField(default='25%', max_length=32, verbose_name='Card Width'),
        ),
        migrations.AlterField(
            model_name='cardswidget',
            name='image_height',
            field=models.CharField(default='100px', max_length=32, verbose_name='Image Height'),
        ),
        migrations.AlterField(
            model_name='cardswidget',
            name='image_width',
            field=models.CharField(default='80px', max_length=32, verbose_name='Image Width'),
        ),
    ]
