# Generated by Django 2.2.11 on 2020-03-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_power_cms', '0023_auto_20200323_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsitem',
            name='open_url_in_new_window',
            field=models.BooleanField(default=False, verbose_name='Open URL In New Window'),
        ),
        migrations.AddField(
            model_name='cardsitem',
            name='url_raw',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='URL'),
        ),
    ]
