[tool.poetry]
name = "fork2gitlab"
version = "0.1.1"
description = "A script to help forking a project to gitlab and keeping it updated downstream"
authors = ["LoveIsGrief <loveisgrief@tuta.io>"]
license = "GPL-3.0-or-later"
readme = "README.md"
homepage = "https://gitlab.com/NamingThingsIsHard/collaboration/fork2gitlab"
repository = "https://gitlab.com/NamingThingsIsHard/collaboration/fork2gitlab"
keywords = [
    "cron",
    "forking",
    "gitlab",
    "script",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: POSIX",
    "Topic :: Software Development :: Version Control :: Git"
]

[tool.poetry.dependencies]
python = "^3.6"
python-gitlab = "^2.1.2"
cliff = "^3.1.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
f2g = 'fork2gitlab.main:main'

[tool.poetry.urls]
"Bug Tracker" = "https://gitlab.com/NamingThingsIsHard/collaboration/fork2gitlab/-/issues"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
