# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-12 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='message',
            unique_together=set([('task', 'receiver_content_type', 'receiver_object_id')]),
        ),
    ]
