
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-05T11:56:50-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "fd5ca38be9a90f6a4fce4a1b683b0adc3f52f770",
 "version": "5.0b16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
