
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-10T06:13:13+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0d55334fcf106d1b1e2926ad5915f127f8a28ee4",
 "version": "1.6.0.post.dev10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
