os: linux
dist: xenial
language: python
branches:
  except:
    - /.*/-pdf

env:
  global:
    - THEANO_FLAGS=floatX=float64,compute_test_value=off
cache:
  directories:
    - "$HOME/.theano"
    - "$HOME/.cache/pip"

stages:
  - name: Housekeeping
  - name: Tests

jobs:
  include:
    - stage: Housekeeping
      name: "Style"
      install:
        - python -m pip install -U pip
        - python -m pip install -U black isort black_nbconvert
      script: ./.ci/travis/check_style.sh
      after_success: skip
      python: "3.7"

    - stage: "Tests"
      python: "3.6"
    - python: "3.7"
    - python: "3.8"

install:
  - travis_retry python -m pip install -U pip
  - travis_retry python -m pip install -U setuptools
  - travis_retry python -m pip install -U numpy pybind11
  - travis_retry python -m pip install -U -r requirements-test.txt
  - travis_retry python -m pip install -U rebound
  - travis_retry python setup.py develop

script:
  - python -m pytest -vs --cov=exoplanet src/exoplanet

after_success:
  - coveralls
