# This file was automatically generated by sub\epyqlib\epyqlib\cli\generateversion.py
__version_build_time__ = '2020-04-03T23:36:24.763771'

__version__ = '2020.4.1'
__sha__ = '304840610669ec763d5220573501b44269187840'
__revision__ = '304840610669ec763d5220573501b44269187840'
