[tool.poetry]
name = "pygame-input"
version = "1.0.0"
description = "pygame-input is a tool to simplify input handling with pygame"
authors = ["Diego Dorn <pygame-input@lama-corp.space>"]
license = "MIT"
readme = "readme.md"
repository = "https://gitlab.com/ddorn/pygame-input"
homepage = "https://gitlab.com/ddorn/pygame-input"
keywords = ['pygame', 'input', 'game', 'joystick']
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Games/Entertainment",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: pygame",
]

[tool.poetry.dependencies]
python = "^3.6"
pygame = "^1.9.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
