
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "branch": "master",
 "date": "2020-04-08T19:37:17+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "25a79c5a8401afd3aa9b6a3a218edcd41a582263",
 "repository": "https://github.com/metawards/MetaWards",
 "version": "0.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
