[tool.poetry]
name = "eyalev-test1"
version = "0.1.2"
description = ""
authors = ["Eyal Levin <eyalev@gmail.com>"]

[tool.poetry.scripts]
test1-cli = "eyalev_test1.main:main"

[tool.poetry.dependencies]
python = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
