[tool.poetry]
name = "kbase_workspace_client"
version = "0.0.2"
description = "KBase Workspace Client and Utilities"
authors = ["KBase Team <info@kbase.us>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6.7"
requests = ">=2"
biopython = "^1.76"

[tool.poetry.dev-dependencies]
pytest = "^5.4.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
