
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "ad4a51f79ab51bb64e91bc716758295dd071072d",
 "version": "1.15.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
