
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-06T16:53:04+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2b89e2f912bb7e9c85640bfba28f2c74d5d047ef",
 "version": "0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
