[tool.poetry]
name = "jse"
version = "0.0.3"
description = "quickly edit json files from the command line"
authors = ["Brian Jubelirer <brian2386@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.4"

[tool.poetry.dev-dependencies]
pytest = "^5.4"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
jse = 'jse:main'