
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-14T20:23:46+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "37db47ccce8bf0d5f8852e00f67713504662e929",
 "version": "1.7.0.post.dev4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
