#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['osxdocker']

package_data = \
{'': ['*']}

install_requires = \
['fire']

extras_require = \
{'test': ['black', 'pytest', 'docker', 'rope']}

entry_points = \
{'console_scripts': ['osxdocker = osxdocker:main']}

setup(name='osxdocker',
      version='0.0.2',
      description='A CLI for working with docker on OSX',
      author='Conor Sheehan',
      author_email='conor.sheehan.dev@gmail.com',
      url='https://github.com/ConorSheehan1/osxdocker',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='>=3',
     )
