language: python

cache:
  pip: true
  timeout: 1000

sudo: false

python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'

os:
- linux
- windows

matrix:
  fast_finish: true
  allow_failures:
    - os: windows

notifications:
  email: false

# repo branches to test
branches:
- master

before_install:
- openssl aes-256-cbc -K $encrypted_f18bc033d6dd_key -iv $encrypted_f18bc033d6dd_iv -in etc/.netrc.enc -out ~/.netrc -d
- chmod 600 ~/.netrc

install:
- pip install -U pip wheel --quiet
- pip install --upgrade setuptools --quiet
- pip install -r requirements.txt --quiet
- pip install pytest
- pip install pytest-coverage
- pip install coveralls
- python setup.py install

script:
- pytest python/sdss_access/tests --cov python/sdss_access --cov-report html

after_success:
- coveralls
