def fetch_packages():
    return [
        {'Code': 'MEA', 'Title': 'Aeroskills Training Package'},
        {'Code': 'AHC', 'Title': 'Agriculture, Horticulture and Conservation and Land Management Training Package'},
        {'Code': 'ACM', 'Title': 'Animal Care and Management Training Package'},
        {'Code': 'AMP', 'Title': 'Australian Meat Processing Training Package'},
        {'Code': 'AUM', 'Title': 'Automotive Manufacturing'},
        {'Code': 'AUR', 'Title': 'Automotive Retail, Service and Repair Training Package'},
        {'Code': 'AVI', 'Title': 'Aviation Training Package'},
        {'Code': 'BSB', 'Title': 'Business Services Training Package'},
        {'Code': 'PMA', 'Title': 'Chemical, Hydrocarbons and Refining'},
        {'Code': 'CHC', 'Title': 'Community Services'},
        {'Code': 'CPC08', 'Title': 'Construction, Plumbing and Services Training Package'},
        {'Code': 'CPC', 'Title': 'Construction, Plumbing and Services Training Package'},
        {'Code': 'CSC', 'Title': 'Correctional Services Training Package'},
        {'Code': 'CUA', 'Title': 'Creative Arts and Culture Training Package'},
        {'Code': 'DEF', 'Title': 'Defence Training Package'},
        {'Code': 'UEP', 'Title': 'Electricity Supply Industry - Generation Sector Training Package'},
        {'Code': 'UEE', 'Title': 'Electrotechnology Training Package'},
        {'Code': 'UEE11', 'Title': 'Electrotechnology Training Package'},
        {'Code': 'FNS', 'Title': 'Financial Services Training Package'},
        {'Code': 'SFL', 'Title': 'Floristry Training Package'},
        {'Code': 'FBP', 'Title': 'Food, Beverage and Pharmaceutical'},
        {'Code': 'FBP', 'Title': 'Food, Beverage and Pharmaceutical'},
        {'Code': 'FSK', 'Title': 'Foundation Skills Training Package'},
        {'Code': 'SIF', 'Title': 'Funeral Services'},
        {'Code': 'MSF', 'Title': 'Furnishing Training Package'},
        {'Code': 'UEG', 'Title': 'Gas Industry Training Package'},
        {'Code': 'SHB', 'Title': 'Hairdressing and Beauty Services Training Package'},
        {'Code': 'HLT', 'Title': 'Health'},
        {'Code': 'ICT', 'Title': 'Information and Communications Technology'},
        {'Code': 'MSL', 'Title': 'Laboratory Operations'},
        {'Code': 'LGA04', 'Title': 'Local Government Training Package'},
        {'Code': 'MEM', 'Title': 'Manufacturing and Engineering'},
        {'Code': 'MSM', 'Title': 'Manufacturing Training Package'},
        {'Code': 'MSA07', 'Title': 'Manufacturing Training Package'},
        {'Code': 'MAR', 'Title': 'Maritime Training Package'},
        {'Code': 'MEM05', 'Title': 'Metal and Engineering Training Package'},
        {'Code': 'NWP', 'Title': 'National Water Training Package'},
        {'Code': 'PMB', 'Title': 'Plastics, Rubber and Cablemaking'},
        {'Code': 'POL', 'Title': 'Police Training Package'},
        {'Code': 'ICP', 'Title': 'Printing and Graphic Arts'},
        {'Code': 'CPP07', 'Title': 'Property Services Training Package'},
        {'Code': 'CPP', 'Title': 'Property Services Training Package'},
        {'Code': 'PUA', 'Title': 'Public Safety'},
        {'Code': 'PSP', 'Title': 'Public Sector Training Package'},
        {'Code': 'PPM', 'Title': 'Pulp & Paper Manufacturing Industry Training Package'},
        {'Code': 'RGR', 'Title': 'Racing and Breeding Training Package'},
        {'Code': 'RII', 'Title': 'Resources and Infrastructure Industry Training Package'},
        {'Code': 'SIR', 'Title': 'Retail Services Training Package'},
        {'Code': 'SFI', 'Title': 'Seafood Industry'},
        {'Code': 'SIS', 'Title': 'Sport, Fitness and Recreation Training Package'},
        {'Code': 'MSS', 'Title': 'Sustainability'},
        {'Code': 'MST', 'Title': 'Textiles, Clothing and Footwear'},
        {'Code': 'LMT07', 'Title': 'Textiles, Clothing and Footwear Training Package'},
        {'Code': 'SIT', 'Title': 'Tourism, Travel and Hospitality Training Package'},
        {'Code': 'TAE', 'Title': 'Training and Education Training Package'},
        {'Code': 'UET', 'Title': 'Transmission, Distribution and Rail Sector'},
        {'Code': 'TLI', 'Title': 'Transport and Logistics Training Package'},
    ]


def find_package_for_code(code):
    for package in fetch_packages():
        if code.startswith(package['Code']):
            return package

    return None