[build-system]
build-backend = "flit_core.buildapi"
requires = [ "flit_core >=2,<3",]


[tool.black]
line-length = 100


[tool.flit.metadata]
module = "atomic_write_path"
author = "Bao Wei"
author-email = "baowei.ur521@gmail.com"
requires = ["atomicwrites >= 1.3"]


[tool.nitpick]
style = "https://raw.githubusercontent.com/dycw/nitpick/master/nitpick-style.toml"
