[tool.poetry]
name = "netblocks3"
version = "0.0.13-rc.0"
description = "Get the Cloud Provider netblocks (Python3 version)"
authors = ["tomasfse"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
