
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-07T18:49:10-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "8454cfa0493a16e3cbbcc356a7cb34d52efec2ec",
 "version": "0.9.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
