
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "55993ea668d7ccfc126801667a60fb21a2bad18a",
 "version": "0.6.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
