[tool.poetry]
name = "piteau"
version = "0.1.1"
description = "Python asynchronous chat"
authors = ["Gabriel Oger"]
license = "MIT"
readme = "docs/index.md"

homepage = "https://pypi.org/project/piteau/"
documentation = "https://piteau.readthedocs.io/"
repository = "https://github.com/cimourdain/piteau"

keywords = [
    "chat",
    "chat-application",
    "asynchronous",
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python",
    "Topic :: Software Development",
    "Topic :: Communications :: Chat",
]

[tool.poetry.dependencies]
python = "^3.6"
aioconsole = "^0.1.16"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
isort = "^4.3.21"
mypy = "^0.770"
mkdocs = "^1.1"
mkdocs-material = ">=4.6.3,<5"
pygments = "==2.5.2"
mkdocstrings = "==0.8"
flake8 = "^3.7.9"

[tool.black]
line-length = 88
skip-string-normalization = true

[tool.isort]
line_length = 88
include_trailing_comma = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

