
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-08T13:57:08-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "45764fc5184a487db3f6730b58d163d1ef8fd054",
 "version": "1.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
