MARIADB: 
    USER: 'new_user'
    PASSWORD: 'new_password'
    HOST: 'localhost'
    PORT: '3306'
    DATABASE: 'DANE-sql-store'
LOGGING: 
    DIR: "./dane-server-logs/"
    LEVEL: "DEBUG"
DANE_SERVER:
    TEMP_FOLDER: "/home/DANE/DANE-data/TEMP/"
    OUT_FOLDER: "/home/DANE/DANE-data/OUT/"
CONFIG:
    REQUIRED: True
