
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-06T13:36:56+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2edced8a18e138aa3b4f4c78f63a1606706ca76c",
 "version": "0.25.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
