# coding: utf-8

"""
    VeeRoute.LSS Merchandiser

    Программный интерфейс для планирования работ торговых предствителей.  # noqa: E501

    OpenAPI spec version: 2.5.156470
    Contact: support@veeroute.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import vrt_lss_merchandiser
from models.inline_response400 import InlineResponse400  # noqa: E501
from vrt_lss_merchandiser.rest import ApiException


class TestInlineResponse400(unittest.TestCase):
    """InlineResponse400 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse400(self):
        """Test InlineResponse400"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vrt_lss_merchandiser.models.inline_response400.InlineResponse400()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
