
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-05T11:05:12-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "46fd4e652644bbde823227a6c6297b71af61632d",
 "version": "5.0b14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
