
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-08T20:52:38-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "1b2a231f2da2f7b50b0f5d24e9af15beae1cdfa3",
 "version": "3.17.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
