
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-06T10:02:06+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c2d8060a592ea60555320c9cd2a1a18668c8a1e0",
 "version": "1.4.0.post.dev101"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
