
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-10T15:02:41+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "a2b7f75bc99a68bf016cbab56fc668a6ce48d25f",
 "version": "1.40"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
