
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-07T21:44:33+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c4bd3769d4c1fa91ef257f79deec2bef9069b383",
 "version": "1.5.1.post.dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
