# coding: utf-8

"""
    VeeRoute.LSS Routing

    Программный интерфейс для получения маршрутов и матриц расстояний  # noqa: E501

    OpenAPI spec version: 2.5.156470
    Contact: support@veeroute.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import vrt_lss_routing
from api.system_api import SystemApi  # noqa: E501
from vrt_lss_routing.rest import ApiException


class TestSystemApi(unittest.TestCase):
    """SystemApi unit test stubs"""

    def setUp(self):
        self.api = api.system_api.SystemApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_check(self):
        """Test case for check

        Проверка доступности сервиса  # noqa: E501
        """
        pass

    def test_version(self):
        """Test case for version

        Получение версии сервиса  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
