# coding: utf-8

"""
    VeeRoute.LSS Routing

    Программный интерфейс для получения маршрутов и матриц расстояний  # noqa: E501

    OpenAPI spec version: 2.5.156470
    Contact: support@veeroute.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import vrt_lss_routing
from models.inline_response501 import InlineResponse501  # noqa: E501
from vrt_lss_routing.rest import ApiException


class TestInlineResponse501(unittest.TestCase):
    """InlineResponse501 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse501(self):
        """Test InlineResponse501"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vrt_lss_routing.models.inline_response501.InlineResponse501()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
