#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['cards']

package_data = \
{'': ['*']}

package_dir = \
{'': 'src'}

install_requires = \
['tinydb', 'typer', 'tabulate']

extras_require = \
{'test': ['pytest', 'pytest-cov']}

entry_points = \
{'console_scripts': ['cards = cards:app']}

setup(name='cards',
      version='0.2.9',
      description='Top-level package for cards.',
      author='Brian Okken',
      author_email='brian+pypi@pythontest.com',
      url='https://github.com/okken/cards',
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
      install_requires=install_requires,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='>=3.7',
     )
