[tool.poetry]
name = "arcade-generator"
version = "0.0.6"
description = "A static site generator"
authors = ["Yabir Benchakhtir <yabirg@protonmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
jinja2 = "*"
markdown = "^3.2.1"
click = "^7.1.1"
pyyaml = "^5.3.1"
livereload = "^2.6.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
