
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-08T12:53:19+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e476546bb9a9c3290e7df681fa7bb8df5f95f07a",
 "version": "5.14.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
