[mypy]
follow_imports = silent
strict_optional = True
warn_redundant_casts = True
warn_unused_ignores = True
check_untyped_defs = True
no_implicit_reexport = True
warn_unused_configs = True
disallow_incomplete_defs = True
disallow_untyped_decorators = True
disallow_untyped_calls = True

disallow_untyped_defs = True
warn_return_any = True

[mypy-pymongo,pymongo.*]
ignore_missing_imports = True

[mypy-bson,bson.*]
ignore_missing_imports = True

[mypy-motor,motor.*]
ignore_missing_imports = True