
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-25T15:45:40-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "bb90bbc7598432be2cc83d018c98e6b22f810916",
 "version": "0.9.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
