
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-12T21:56:24-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "9ad431b905950d17317cda4666434ea95b74e89e",
 "version": "2020.4.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
