name: build

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools setuptools_scm
          python setup.py install
      - name: pytest and coverage
        run: |
          python -m pip install --upgrade pip
          pip install pytest-pep8
          pip install pytest-cov==2.5.0
      - name: Upload coverage to codeclimate
        uses: paambaati/codeclimate-action@v2.5.6
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: py.test tests --doctest-modules --pep8 src/aoc -v --cov src/aoc --cov-report xml
          coverageLocations:
            "${{github.workspace}}/coverage.xml:coverage.py"
  test-deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch history and tags
        run: |
          git fetch --prune --unshallow
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel setuptools_scm
          python setup.py sdist bdist_wheel bdist_egg
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@37e305e7413032d8422456179fee28fac7d25187
        with:
          user: __token__
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/