# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pull request

on:
  pull_request:
    branches:
      - master
    tags:
      - '!*' # Do not execute on tags
    paths:
      - '!*.rst'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python setup.py install
      - name: pytest and coverage
        run: |
          python -m pip install --upgrade pip
          pip install pytest-pep8
          pip install pytest-cov==2.5.0
          py.test aoc --doctest-modules --pep8 aoc -v --cov aoc --cov-report xml