# Autogenerated by Astropy-affiliated package baseband's setup.py on 2020-04-05 17:05:04 UTC
import datetime

version = "3.1.1"
githash = "6aab8d4b8869cc2351b991a94c6ed599d22df3fa"


major = 3
minor = 1
bugfix = 1

version_info = (major, minor, bugfix)

release = True
timestamp = datetime.datetime(2020, 4, 5, 17, 5, 4)
debug = False

astropy_helpers_version = "4.0.1"
