
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-07T22:37:13+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "67acf64d316956c5ef5539a9c0fbe3b594494baa",
 "version": "0.54.0-dev.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
