# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-22 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_passwordreset', '0005_auto_20181017_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpasswordtoken',
            name='is_long_token',
            field=models.BooleanField(default=False),
        ),
    ]
