# AUTOGENERATED! DO NOT EDIT! File to edit: 01_exceptions.ipynb (unless otherwise specified).

__all__ = ['KeyedException', 'ApplyKeyedException']

# Cell
class KeyedException(Exception):

    def __init__(self, *args, path):
        super().__init__(*args)
        self.path = path

class ApplyKeyedException(KeyedException):

    def __init__(self, *args, path, value):
        super().__init__(*args, path=path)
        self.value = value