
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-14T12:51:37+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "aef38f023808c315c67bafa57fb10f523c7eb0ef",
 "version": "1.6.1.post.dev10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
