[tool.poetry]

name = "typefit"
version = "0.2.0"

description = "Fits JSON values into Python type-anotated objects"
license = "WTFPL"
authors = [
    "Rémy Sanchez <remy.sanchez@hyperthese.net>"
]

readme = "README.md"

repository = "https://github.com/Xowap/typefit/"
homepage = "https://github.com/Xowap/typefit/"

keywords = ["typing", "json", "api"]


[tool.poetry.dependencies]

python = "^3.7"
pendulum = { version = "^2.0", optional = true }
httpx = { version = "^0.7", optional = true }


[tool.poetry.dev-dependencies]

pytest = "^5.2.1"
ipython = "*"
sphinx = "^2.2"
importlib-metadata = "^0.23.0"
isort = "^4.3"
black = "^19.10b0"
httpbin = "^0.7.0"


[tool.poetry.extras]

dates = ["pendulum"]
api = ["httpx"]
