# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-22 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='category'),
            preserve_default=False,
        ),
    ]
