
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-06T10:31:59-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "fe3e59374407e5b25ef8ffd61a3d7f7c13fb76ac",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
