
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-12T13:07:18+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1dff48e2ae5fed1c7f832e8f1036c65ef600dc11",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
