# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'peopleEdit.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_peopleDiag(object):
    def setupUi(self, peopleDiag):
        peopleDiag.setObjectName("peopleDiag")
        peopleDiag.resize(506, 418)
        peopleDiag.setSizeGripEnabled(True)
        peopleDiag.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(peopleDiag)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formGroupBox = QtWidgets.QGroupBox(peopleDiag)
        self.formGroupBox.setObjectName("formGroupBox")
        self.formLayout = QtWidgets.QFormLayout(self.formGroupBox)
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(self.formGroupBox)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.nameEdit = QtWidgets.QLineEdit(self.formGroupBox)
        self.nameEdit.setObjectName("nameEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameEdit)
        self.genderLabel = QtWidgets.QLabel(self.formGroupBox)
        self.genderLabel.setObjectName("genderLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.genderLabel)
        self.genderBox = QtWidgets.QFrame(self.formGroupBox)
        self.genderBox.setObjectName("genderBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.genderBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.maleRadio = QtWidgets.QRadioButton(self.genderBox)
        self.maleRadio.setObjectName("maleRadio")
        self.horizontalLayout.addWidget(self.maleRadio)
        self.femaleRadio = QtWidgets.QRadioButton(self.genderBox)
        self.femaleRadio.setObjectName("femaleRadio")
        self.horizontalLayout.addWidget(self.femaleRadio)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.genderBox)
        self.birthdateLabel = QtWidgets.QLabel(self.formGroupBox)
        self.birthdateLabel.setObjectName("birthdateLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.birthdateLabel)
        self.dateEdit = QtWidgets.QDateEdit(self.formGroupBox)
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(1980, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dateEdit)
        self.addressLabel = QtWidgets.QLabel(self.formGroupBox)
        self.addressLabel.setObjectName("addressLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.addressLabel)
        self.addressEdit = QtWidgets.QPlainTextEdit(self.formGroupBox)
        self.addressEdit.setTabChangesFocus(True)
        self.addressEdit.setObjectName("addressEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.addressEdit)
        self.locationLabel = QtWidgets.QLabel(self.formGroupBox)
        self.locationLabel.setObjectName("locationLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.locationLabel)
        self.locationEdit = QtWidgets.QLineEdit(self.formGroupBox)
        self.locationEdit.setObjectName("locationEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.locationEdit)
        self.label = QtWidgets.QLabel(self.formGroupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label)
        self.birthplaceEdit = QtWidgets.QLineEdit(self.formGroupBox)
        self.birthplaceEdit.setObjectName("birthplaceEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.birthplaceEdit)
        self.verticalLayout.addWidget(self.formGroupBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(peopleDiag)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.nameLabel.setBuddy(self.nameEdit)
        self.birthdateLabel.setBuddy(self.dateEdit)
        self.addressLabel.setBuddy(self.addressEdit)
        self.locationLabel.setBuddy(self.locationEdit)
        self.label.setBuddy(self.birthplaceEdit)

        self.retranslateUi(peopleDiag)
        self.buttonBox.accepted.connect(peopleDiag.accept)
        self.buttonBox.rejected.connect(peopleDiag.reject)
        QtCore.QMetaObject.connectSlotsByName(peopleDiag)
        peopleDiag.setTabOrder(self.nameEdit, self.maleRadio)
        peopleDiag.setTabOrder(self.maleRadio, self.femaleRadio)
        peopleDiag.setTabOrder(self.femaleRadio, self.dateEdit)
        peopleDiag.setTabOrder(self.dateEdit, self.birthplaceEdit)
        peopleDiag.setTabOrder(self.birthplaceEdit, self.addressEdit)
        peopleDiag.setTabOrder(self.addressEdit, self.locationEdit)

    def retranslateUi(self, peopleDiag):
        _translate = QtCore.QCoreApplication.translate
        peopleDiag.setWindowTitle(_translate("peopleDiag", "Dialog"))
        self.formGroupBox.setTitle(_translate("peopleDiag", "Identité"))
        self.nameLabel.setText(_translate("peopleDiag", "Prénom et &nom"))
        self.genderLabel.setText(_translate("peopleDiag", "Genre"))
        self.maleRadio.setText(_translate("peopleDiag", "Mascu&lin"))
        self.femaleRadio.setText(_translate("peopleDiag", "F&éminin"))
        self.birthdateLabel.setText(_translate("peopleDiag", "&Date de naissance"))
        self.addressLabel.setText(_translate("peopleDiag", "&Adresse"))
        self.locationLabel.setText(_translate("peopleDiag", "Emplacemen&t"))
        self.label.setText(_translate("peopleDiag", "Lieu de naissance"))
