[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "aria2p"
version = "0.9.0"
description = "Command-line tool and library to interact with an aria2c daemon process with JSON-RPC."
authors = ["Timothée Mazzucotelli <pawamoy@pm.me>"]
license = "ISC"
readme = "README.md"
repository = "https://github.com/pawamoy/aria2p"
homepage = "https://github.com/pawamoy/aria2p"
keywords = ["aria2", "aria2c", "aria2-cli"]
packages = [ { include = "aria2p", from = "src" } ]
include = [
    "README.md",
    "pyproject.toml"
]

[tool.poetry.dependencies]
python = "^3.6"
requests = "*"
loguru = "*"
websocket_client = "*"
asciimatics = { version = "*", optional = true }

[tool.poetry.dev-dependencies]
bandit = "^1.5"
coverage = "^5.0"
flake8 = "^3.6"
git-changelog = "^0.2.0"
ipython = "^7.2"
isort = { version = "^4.3", extras = ["pyproject"] }
jinja2-cli = "^0.7.0"
mkdocs = "^1.1"
mkdocstrings = "^0.10.0"
mkdocs-material = "^4.6.0"
mypy = "^0.761"
pyinstaller = "^3.5"
pylint = { git = "https://github.com/PyCQA/pylint.git" }
pytest = "^4.3"
pytest-cov = "^2.8"
pytest-sugar = "^0.9.2"
pytest-xdist = "^1.26"
responses = "^0.10.5"
safety = "^1.8"
toml = "^0.10.0"
black = "^19.10b0"

[tool.poetry.extras]
tui = ["asciimatics"]

[tool.poetry.scripts]
aria2p = "aria2p.cli:main"

[tool.black]
line-length = 120

[tool.isort]
line_length = 120
not_skip = "__init__.py"
multi_line_output = 3
force_single_line = false
balanced_wrapping = true
default_section = "THIRDPARTY"
known_first_party = "aria2p"
include_trailing_comma = true

[tool.pylint.options]
disable = """
  bad-continuation,
  too-many-lines,
  too-many-public-methods,
  too-many-locals,
  too-many-statements,
  too-many-arguments,
  too-many-instance-attributes,
  too-many-branches,
  too-few-public-methods,
  duplicate-code
"""
max-line-length = "120"
