
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-08T11:55:37+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a9c49c697152f480cd94c61e59d49de8d0e184a3",
 "version": "1.5.1.post.dev11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
