[tool.poetry]
name = "pecho"
version = "0.3.0"
description = "Easy way to write things like status bars"
authors = ["Nihaal Sangha <18350092+OrangutanGaming@users.noreply.github.com>"]
license = "MIT"
include = ["LICENSE"]
readme = "README.md"
repository = "https://github.com/OrangutanGaming/pecho"

[tool.poetry.dependencies]
python = "^3.8"
colorama = "^0.4.3"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
isort = "^4.3.21"

[tool.black]
line-length = 120
target-version = ['py38']
skip-string-normalization = true
include = '\.pyi?$'

[tool.isort]
line_length = 120

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
