
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-08T11:52:23-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e43c6c138f79066cd77251d125935808dcde0a74",
 "version": "1.2.0rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
