[tool.poetry]
name = "ghostwriter"
version = "0.1.0"
description = "GhostWriter lets you edit a website via lektor, a flexible and powerful static content management system for building complex and beautiful websites out of flat files - for people who do not want to make a  compromise between a CMS and a static blog engine."
authors = ["hiro <hiro@torproject.org>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^2.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
