# coding: utf-8

"""
    VeeRoute.LSS Routing

    Программный интерфейс для получения маршрутов и матриц расстояний  # noqa: E501

    OpenAPI spec version: 2.5.156470
    Contact: support@veeroute.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class RouteLeg(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'steps': 'list[RouteStep]',
        'statistics': 'RouteStatistics'
    }

    attribute_map = {
        'steps': 'steps',
        'statistics': 'statistics'
    }

    def __init__(self, steps=None, statistics=None):  # noqa: E501
        """RouteLeg - a model defined in Swagger"""  # noqa: E501
        self._steps = None
        self._statistics = None
        self.discriminator = None
        if steps is not None:
            self.steps = steps
        if statistics is not None:
            self.statistics = statistics

    @property
    def steps(self):
        """Gets the steps of this RouteLeg.  # noqa: E501

        Шаги, выполнение которых требуется для прохождения отрезка маршрута.  # noqa: E501

        :return: The steps of this RouteLeg.  # noqa: E501
        :rtype: list[RouteStep]
        """
        return self._steps

    @steps.setter
    def steps(self, steps):
        """Sets the steps of this RouteLeg.

        Шаги, выполнение которых требуется для прохождения отрезка маршрута.  # noqa: E501

        :param steps: The steps of this RouteLeg.  # noqa: E501
        :type: list[RouteStep]
        """

        self._steps = steps

    @property
    def statistics(self):
        """Gets the statistics of this RouteLeg.  # noqa: E501


        :return: The statistics of this RouteLeg.  # noqa: E501
        :rtype: RouteStatistics
        """
        return self._statistics

    @statistics.setter
    def statistics(self, statistics):
        """Sets the statistics of this RouteLeg.


        :param statistics: The statistics of this RouteLeg.  # noqa: E501
        :type: RouteStatistics
        """

        self._statistics = statistics

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RouteLeg, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RouteLeg):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
