[tool.poetry]
name = "django-getpaid"
version = "2.0.0-rc.6"
description = "Multi-broker payment processor for Django."
authors = ["Dominik Kozaczko <dominik@kozaczko.info>"]
license = "MIT"
readme = "README.rst"
repository = "https://github.com/django-getpaid/django-getpaid"
packages = [
    { include = "getpaid" }
]

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.23.0"
django-model-utils = "^4.0.0"
pendulum = "^2.0.5"
#django = "~2.2 || ~3.0"
swapper = "^1.1.2"
sphinx-rtd-theme = "^0.4.3"

[tool.poetry.dev-dependencies]
tox = "^3.14.5"
factory-boy = "^2.12.0"
ipdb = "^0.13.1"
pre-commit = "^2.1.1"
pytest = {version = "^5.3.5", optional=true}
codecov = {version="^2.0.16", optional=true}
coverage = {version="^5.0.3", optional=true}
requests-mock = {version="^1.7.0", optional=true}
pytest-cov = {version = "^2.8.1", optional = true}
pytest-django = {version = "^3.8.0", optional = true}
sphinx = {version = "^3", optional = true}
black = "^19.10b0"

[tool.poetry.extras]
docs = ["sphinx"]
test = ["pytest", "codecov", "coverage", "request-mock", "pytest-cov", "pytest-django"]

[tool.black]
line-length = 88
target-version = ['py36']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.cache
    | \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.pytest_cache
    | \.tox
    | \.venv
    | __pycache__
    | _build
    | buck-out
    | build
    | dist
    | docs
    | migrations
  )/

)
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = false
line_length = 88
known_first_party = ["getpaid"]
known_third_party = ["django", "factory", "orders", "pendulum", "requests", "swapper"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
