[tool.poetry]
name = "sir_hiss"
readme = "README.md"
version = "0.0.4"
description = "Run the relevant tools for a repository"
repository = "https://nest.pijul.com/gwenzek/sir_hiss"
authors = ["gwenzek"]

[project]
readme = "README.md"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88

[tool.poetry.scripts]
sir_hiss = "sir_hiss:_main"

[tool.poetry.dependencies]
python = "^3.6"
func_argparse = "^1.1.1"
toml = "^0.10.0"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
isort = "^4.3.21"
pytest = "^5.3.5"
