# coding: utf-8

"""
    Brawl Stars API

    Brawl Stars API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ClubRanking(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tag': 'str',
        'name': 'str',
        'trophies': 'int',
        'rank': 'int',
        'member_count': 'int'
    }

    attribute_map = {
        'tag': 'tag',
        'name': 'name',
        'trophies': 'trophies',
        'rank': 'rank',
        'member_count': 'memberCount'
    }

    def __init__(self, tag=None, name=None, trophies=None, rank=None, member_count=None):  # noqa: E501
        """ClubRanking - a model defined in Swagger"""  # noqa: E501
        self._tag = None
        self._name = None
        self._trophies = None
        self._rank = None
        self._member_count = None
        self.discriminator = None
        if tag is not None:
            self.tag = tag
        if name is not None:
            self.name = name
        if trophies is not None:
            self.trophies = trophies
        if rank is not None:
            self.rank = rank
        if member_count is not None:
            self.member_count = member_count

    @property
    def tag(self):
        """Gets the tag of this ClubRanking.  # noqa: E501


        :return: The tag of this ClubRanking.  # noqa: E501
        :rtype: str
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """Sets the tag of this ClubRanking.


        :param tag: The tag of this ClubRanking.  # noqa: E501
        :type: str
        """

        self._tag = tag

    @property
    def name(self):
        """Gets the name of this ClubRanking.  # noqa: E501


        :return: The name of this ClubRanking.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ClubRanking.


        :param name: The name of this ClubRanking.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def trophies(self):
        """Gets the trophies of this ClubRanking.  # noqa: E501


        :return: The trophies of this ClubRanking.  # noqa: E501
        :rtype: int
        """
        return self._trophies

    @trophies.setter
    def trophies(self, trophies):
        """Sets the trophies of this ClubRanking.


        :param trophies: The trophies of this ClubRanking.  # noqa: E501
        :type: int
        """

        self._trophies = trophies

    @property
    def rank(self):
        """Gets the rank of this ClubRanking.  # noqa: E501


        :return: The rank of this ClubRanking.  # noqa: E501
        :rtype: int
        """
        return self._rank

    @rank.setter
    def rank(self, rank):
        """Sets the rank of this ClubRanking.


        :param rank: The rank of this ClubRanking.  # noqa: E501
        :type: int
        """

        self._rank = rank

    @property
    def member_count(self):
        """Gets the member_count of this ClubRanking.  # noqa: E501


        :return: The member_count of this ClubRanking.  # noqa: E501
        :rtype: int
        """
        return self._member_count

    @member_count.setter
    def member_count(self, member_count):
        """Sets the member_count of this ClubRanking.


        :param member_count: The member_count of this ClubRanking.  # noqa: E501
        :type: int
        """

        self._member_count = member_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ClubRanking, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClubRanking):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
