
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-04T22:30:13+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "31e1d6c598e1a23b1873773d4d9fa7e1709c915e",
 "version": "0.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
