name: Build
on: push

env:
  target_py_version: 3.8

jobs:
  lint:
    name: Lint Code Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.target_py_version }}
      - name: Install Dependencies
        run: pip install .[dev,typing]
      - name: Run Black
        run: invoke black --check
        if: "always()"
      - name: Run Flake8
        run: invoke flake8
        if: "always()"
      - name: Run isort
        run: invoke isort --check
        if: "always()"
      - name: Run MyPy
        run: invoke mypy
        if: "always()"

  test:
    name: Run Tests (Python ${{ matrix.python }}, MongoDB ${{ matrix.mongodb }})
    runs-on: ubuntu-latest
    if: "always()"
    strategy:
      matrix:
        python: ["3.7", "3.8"]
        mongodb: ["4.0", "4.2"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install Dependencies
        run: pip install .[dev]
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.2.0
        with:
          mongodb-version: ${{ matrix.mongodb }}
      - name: Run Pytest
        run: invoke test --coverage
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v1
        with:
          name: Coverage Report
          path: htmlcov

  build:
    name: Build Package
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # We need to fetch all commits up to the last tag to read the correct version number
          fetch-depth: 50
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.target_py_version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U pep517
      - name: Build Package
        run: python -m pep517.build .
        env:
          SKIP_CYTHON: 1
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: PyPI Files
          path: dist

  deploy:
    name: Deploy to PyPI
    needs: [lint, test, build]
    if: "success() && startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.target_py_version }}
      - name: Install Dependencies
        run: pip install twine
      - name: Get Build Artifacts
        uses: actions/download-artifact@v1
        with:
          name: PyPI Files
          path: dist
      - name: Validate Build Artifacts
        run: twine check dist/*
      - name: Upload to PyPI
        run: twine upload --non-interactive dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PIPY_TOKEN }}
