
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-08T03:48:44+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a51b140f476817848a0ce36d6393ae1440a193d4",
 "version": "1.5.1.post.dev6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
