
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-11T12:23:43-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9dd79f345a453adeb196fba1e21d6d4bd1aac442",
 "version": "0.8.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
