"""Spotify response stated codes.

Reference:
    https://developer.spotify.com/documentation/web-api/#response-status-codes
"""

RESPONSE_OK = 200
RESPONSE_CREATED = 201
RESPONSE_ACCEPTED = 202
RESPONSE_NO_CONTENT = 204

RESPONSE_NOT_MODIFIED = 304

RESPONSE_BAD_REQUEST = 400
RESPONSE_UNAUTHORIZED = 401
RESPONSE_FORBIDDEN = 403
RESPONSE_NOT_FOUND = 404
RESPONSE_TOO_MANY_REQUESTS = 429

RESPONSE_INTERNAL_SERVER_ERROR = 500
RESPONSE_BAD_GATEWAY = 502
RESPONSE_SERVICE_UNAVAILABLE = 503
