# BSD 3-Clause &quot;New&quot; or &quot;Revised&quot; License (BSD-3-Clause)

# flake8: noqa

"""
A Python client package for accessing data from an API that follows the Consumer Data Standards (CDS).
CDS repo: https://consumerdatastandardsaustralia.github.io/standards

Generated with the Swagger-Codegen CLI from a Swagger specification file of the Consumer Data Standards.
Do not edit this file manually. CLI repo: https://github.com/swagger-api/swagger-codegen
    
The package is NOT part of the official Consumer Data Standards' project nor any API implementation of the Standards.
Package repo: https://github.com/stephenmccalman/cds-python-api-client
"""


# import apis into api package
from cds.api.accounts_api import AccountsApi
from cds.api.banking_api import BankingApi
from cds.api.common_api import CommonApi
from cds.api.customer_api import CustomerApi
from cds.api.direct_debits_api import DirectDebitsApi
from cds.api.discovery_api import DiscoveryApi
from cds.api.payees_api import PayeesApi
from cds.api.products_api import ProductsApi
from cds.api.scheduled_payments_api import ScheduledPaymentsApi

