# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"create_sub_dirs": "00_dir_tree.ipynb",
         "create_test_dir": "00_dir_tree.ipynb",
         "get_dirs_files": "00_dir_tree.ipynb",
         "tree": "00_dir_tree.ipynb"}

modules = ["dir_tree.py"]

doc_url = "https://ayasyrev.github.io/dir_tree/"

git_url = "https://github.com/ayasyrev/dir_tree/tree/master/"

def custom_doc_links(name): return None
