# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from spaceone.api.identity.v1 import provider_pb2 as spaceone_dot_api_dot_identity_dot_v1_dot_provider__pb2


class ProviderStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.create = channel.unary_unary(
        '/spaceone.api.identity.v1.Provider/create',
        request_serializer=spaceone_dot_api_dot_identity_dot_v1_dot_provider__pb2.CreateProviderRequest.SerializeToString,
        response_deserializer=spaceone_dot_api_dot_identity_dot_v1_dot_provider__pb2.ProviderInfo.FromString,
        )
    self.update = channel.unary_unary(
        '/spaceone.api.identity.v1.Provider/update',
        request_serializer=spaceone_dot_api_dot_identity_dot_v1_dot_provider__pb2.UpdateProviderRequest.SerializeToString,
        response_deserializer=spaceone_dot_api_dot_identity_dot_v1_dot_provider__pb2.ProviderInfo.FromString,
        )
    self.delete = channel.unary_unary(
        '/spaceone.api.identity.v1.Provider/delete',
        request_serializer=spaceone_dot_api_dot_identity_dot_v1_dot_provider__pb2.ProviderRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.get = channel.unary_unary(
        '/spaceone.api.identity.v1.Provider/get',
        request_serializer=spaceone_dot_api_dot_identity_dot_v1_dot_provider__pb2.ProviderRequest.SerializeToString,
        response_deserializer=spaceone_dot_api_dot_identity_dot_v1_dot_provider__pb2.ProviderInfo.FromString,
        )
    self.list = channel.unary_unary(
        '/spaceone.api.identity.v1.Provider/list',
        request_serializer=spaceone_dot_api_dot_identity_dot_v1_dot_provider__pb2.ProviderQuery.SerializeToString,
        response_deserializer=spaceone_dot_api_dot_identity_dot_v1_dot_provider__pb2.ProvidersInfo.FromString,
        )


class ProviderServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def create(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def update(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def list(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ProviderServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'create': grpc.unary_unary_rpc_method_handler(
          servicer.create,
          request_deserializer=spaceone_dot_api_dot_identity_dot_v1_dot_provider__pb2.CreateProviderRequest.FromString,
          response_serializer=spaceone_dot_api_dot_identity_dot_v1_dot_provider__pb2.ProviderInfo.SerializeToString,
      ),
      'update': grpc.unary_unary_rpc_method_handler(
          servicer.update,
          request_deserializer=spaceone_dot_api_dot_identity_dot_v1_dot_provider__pb2.UpdateProviderRequest.FromString,
          response_serializer=spaceone_dot_api_dot_identity_dot_v1_dot_provider__pb2.ProviderInfo.SerializeToString,
      ),
      'delete': grpc.unary_unary_rpc_method_handler(
          servicer.delete,
          request_deserializer=spaceone_dot_api_dot_identity_dot_v1_dot_provider__pb2.ProviderRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'get': grpc.unary_unary_rpc_method_handler(
          servicer.get,
          request_deserializer=spaceone_dot_api_dot_identity_dot_v1_dot_provider__pb2.ProviderRequest.FromString,
          response_serializer=spaceone_dot_api_dot_identity_dot_v1_dot_provider__pb2.ProviderInfo.SerializeToString,
      ),
      'list': grpc.unary_unary_rpc_method_handler(
          servicer.list,
          request_deserializer=spaceone_dot_api_dot_identity_dot_v1_dot_provider__pb2.ProviderQuery.FromString,
          response_serializer=spaceone_dot_api_dot_identity_dot_v1_dot_provider__pb2.ProvidersInfo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'spaceone.api.identity.v1.Provider', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
