# coding: utf-8

"""
    Brawl Stars API

    Brawl Stars API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.rankings_api import RankingsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRankingsApi(unittest.TestCase):
    """RankingsApi unit test stubs"""

    def setUp(self):
        self.api = api.rankings_api.RankingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_brawler_rankings(self):
        """Test case for get_brawler_rankings

        Get brawler rankings for a country or global rankings.  # noqa: E501
        """
        pass

    def test_get_club_rankings(self):
        """Test case for get_club_rankings

        Get club rankings for a country or global rankings.  # noqa: E501
        """
        pass

    def test_get_player_rankings(self):
        """Test case for get_player_rankings

        Get player rankings for a country or global rankings.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
