# coding: utf-8

"""
    Brawl Stars API

    Brawl Stars API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.player_ranking_club import PlayerRankingClub  # noqa: E501
from swagger_client.rest import ApiException


class TestPlayerRankingClub(unittest.TestCase):
    """PlayerRankingClub unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlayerRankingClub(self):
        """Test PlayerRankingClub"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.player_ranking_club.PlayerRankingClub()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
