
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-03T15:52:45-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "ce34c3c071466ca1f90d5d74fc23bb95d57e5765",
 "version": "1.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
