[tool.poetry]
name = "investify"
version = "0.0.3"
description = "Get automated price alert based on investing.com prices"
authors = ["Abhishek Guha <abhi.workspace@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/abhi-g80/investify"
repository = "https://github.com/abhi-g80/investify"
keywords = ["investing", "whatsapp", "finance", "python", "automation"]
classifiers = [
    "Environment :: Console",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Utilities",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
include = [
    "LICENSE.txt",
]

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.1.1"
requests = "^2.23.0"
twilio = "^6.38.0"
lxml = "^4.5.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
investify = 'investify.investify:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
