[tool.poetry]
name = "arfs_gen"
version = "1.1.0"
description = "Library to generate toy data for machine learning experiments in the context of all-relevant feature selection."
authors = ["Lukas Pfannschmidt <lukas@lpfann.me>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
numpy = "^1"
scikit-learn = "~0"

[tool.poetry.dev-dependencies]
pytest = "^5.3.2"
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
