name: hypothesis-pandas

dependencies:
  - python=3.7.*
  - pip
  - pip:

    - pandas >= 0.25
    - functional-itertools

      # testing
    - hypothesis
    - pytest
    - pytest-cov
    - pytest-randomly
    - pytest-xdist == 1.29

    # publishing
    - bump2version
    - flit
    - keyring
    - pre-commit
