[tool.poetry]
name = "notiforward"
version = "0.1.0"
description = ""
authors = ["rendaw"]

[tool.poetry.dependencies]
python = "^3.6"
dbus-python = "^1.2.16"
pygobject = "^3.36.0"
requests = "^2.23.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
