
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-03T10:04:39-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "1d4f15e3e11b5dad40dd2f1d84e3c1cb37d460a9",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
