# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='galaxy-fds-sdk',
    version='1.4.32',
    description='Python sdk for Galaxy FDS',
    python_requires='!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,<4.0,>=2.7',
    author='hujianxin',
    author_email='hujianxin@xiaomi.com',
    entry_points={
        "console_scripts": [
            "fds = fds.fds_cli:main", "fdscli = fds.fdscli_cli:main"
        ]
    },
    packages=['fds', 'fds.auth', 'fds.auth.signature', 'fds.model', 'test'],
    package_dir={"": "."},
    package_data={},
    install_requires=[
        'argcomplete==1.*,>=1.9.0', 'click==7.*,>=7.0.0', 'crcmod==1.*,>=1.7.0',
        'enum34; python_version == "3.4.*" and python_version >= "3.4.0"',
        'futures; python_version == "2.7.*" and python_version >= "2.7.0"',
        'pathlib2==2.*,>=2.2.0; python_version == "2.7.*" and python_version >= "2.7.0"',
        'requests==2.*,>=2.21.0'
    ],
    extras_require={
        "dev": [
            "autopep8==1.*,>=1.4.0", "pep8==1.*,>=1.7.0", "rope==0.*,>=0.14.0"
        ]
    },
)
