
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-08T17:54:24+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "2ceb110b0f98032c80a165ce6ce50c9a6496c355",
 "version": "0.2.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
