trigger:
  - master

jobs:
  - job: "Test"
    pool:
      vmImage: "vs2017-win2016"
    strategy:
      matrix:
        py37:
          python.version: "3.7"
          tox.env: py37
        py38:
          python.version: "3.8"
          tox.env: py38

    steps:
      - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
        displayName: Add conda to PATH

      - script: conda create --yes --quiet --name exoplanetTest python=$(python.version) pip
        displayName: Create Anaconda environment

      - script: conda install --yes --quiet --name exoplanetTest numpy "scipy<1.4.0" mkl-service libpython m2w64-toolchain astropy matplotlib theano
        displayName: Install dependencies from defaults channel

      - script: conda install --yes --quiet --name exoplanetTest -c conda-forge pybind11 celerite
        displayName: Install dependencies from conda-forge channel

      - script: |
          call activate exoplanetTest
          python -m pip install -U pip
          python -m pip install -r requirements-test.txt
          python -m pip install -e .
        displayName: Install dependencies from PyPI

      - script: |
          call activate exoplanetTest
          python -m pytest -vs src/exoplanet
        displayName: Run tests
