[tool.poetry]
name = "coldtype"
version = "0.0.1"
description = ""
authors = ["Rob Stenson <rob@goodhertz.com>"]

[tool.poetry.dependencies]
python = ">=3.6.8"
fontTools = "^4.7.0"
unicodedata2 = "^13.0.0"
freetype-py = "^2.1.0"
fontPens = "^0.2.4"
skia-pathops = "^0.4.0"
websockets = "^8.1"
watchdog = "^0.10.2"
uharfbuzz = "^0.9.1"
booleanOperations = "^0.9.0"
noise = "^1.2.2"

[tool.poetry.dev-dependencies]
pytest = "^3.4"