[tool.poetry]
name = "scilib"
version = "0.0.10"
description = "scilib"
license = "MIT"
readme = "README.md"
authors = ["phyng <phyngk@gmail.com>"]
homepage = "https://github.com/phyng/scilib"
repository = "https://github.com/phyng/scilib"
classifiers = [
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
]

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^1.0.3"
jupyter = "^1.0.0"
numpy = "^1.18.2"
xlrd = "^1.2.0"
matplotlib = "^3.2.1"
scipy = "^1.4.1"
requests = "^2.23.0"
orjson = "^2.6.3"

[tool.poetry.dev-dependencies]
sphinx = "^2.4.4"
twine = "^3.1.1"
coverage = "^5.0.3"
flake8 = "^3.7.9"
sphinx_rtd_theme = "^0.4.3"
wheel = "^0.34.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
