
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-09T01:48:28+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f9a4cadc73c42d1dc12e8ea3a379b61d5a6cd0e7",
 "version": "1.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
