
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-08T13:16:19+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3ca16662dfbc0728299c8630ae80ff461074a660",
 "version": "2.0.0-beta.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
