[build-system]
requires = [
    "read_version[toml] ~= 0.3.0",
    "setuptools >= 43.0.0",
    "wheel ~= 0.32"
]
build-backend = "setuptools.build_meta"

[tool.read_version]
version = "src.check_wheel_contents.__init__:__version__"
