---
name: Linting and Testing
on: [push]

jobs:
  lint-test:
    name: Check python code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          python -m pip install black flake8

      - name: Run black
        run: black --quiet --check .

      - name: Run flake8
        run: flake8 --show-source --statistics
