
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-14T19:42:12+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "038d312da5b7ad44612da0814e71daa05c5544c9",
 "version": "1.7.0.post.dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
