# coding: utf-8

"""
    VeeRoute.LSS Lastmile

    Программный интерфейс для универсального планирования задач последней мили  # noqa: E501

    OpenAPI spec version: 2.5.156470
    Contact: support@veeroute.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import vrt_lss_lastmile
from api.analytics_api import AnalyticsApi  # noqa: E501
from vrt_lss_lastmile.rest import ApiException


class TestAnalyticsApi(unittest.TestCase):
    """AnalyticsApi unit test stubs"""

    def setUp(self):
        self.api = api.analytics_api.AnalyticsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_analytics(self):
        """Test case for analytics

        Аналитика результатов планирования  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
