# coding: utf-8

"""
    VeeRoute.LSS Lastmile

    Программный интерфейс для универсального планирования задач последней мили  # noqa: E501

    OpenAPI spec version: 2.5.156470
    Contact: support@veeroute.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import vrt_lss_lastmile
from models.inline_response504 import InlineResponse504  # noqa: E501
from vrt_lss_lastmile.rest import ApiException


class TestInlineResponse504(unittest.TestCase):
    """InlineResponse504 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse504(self):
        """Test InlineResponse504"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vrt_lss_lastmile.models.inline_response504.InlineResponse504()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
