[tool.poetry]
name = "CloudMage-JinjaUtils"
version = "1.0.6"
description = "Quickly and easily define, load, render and write Jinja templates."
authors = ["Rich Nason <rnason@cloudmage.io>"]
maintainers = ["Rich Nason <rnason@cloudmage.io>"]
license = "GPL-3.0-or-later"
readme = "README.md"
include = [
    "CHANGELOG.md",
    "LICENSE"
]
homepage = "https://github.com/CloudMages/PyPkgs-JinjaUtils"
repository = "https://github.com/CloudMages/PyPkgs-JinjaUtils"
documentation = "https://github.com/CloudMages/PyPkgs-JinjaUtils"
keywords = [
    "Packages",
    "CloudMage",
    "Jinja"
]

classifiers = [
    "Environment :: Console",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Documentation",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

packages = [
    {include = "cloudmage"}
]

[tool.poetry.urls]
"Releases" = "https://github.com/CloudMages/PyPkgs-JinjaUtils/releases"
"Issues" = "https://github.com/CloudMages/PyPkgs-JinjaUtils/issues"

[tool.poetry.dependencies]
python = "^3.6"
jinja2 = "^2.11.1"

[tool.poetry.dev-dependencies]
pytest = "^4.6"
coverage = "^5.0.3"
pylint = "^2.4.4"

[tool.poetry.scripts]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

