# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'controller.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Controller(object):
    def setupUi(self, Controller):
        Controller.setObjectName("Controller")
        Controller.resize(1000, 650)
        Controller.setWindowTitle("Snitch")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/eyecandy/ui/icons/snitch.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Controller.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Controller)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setHandleWidth(9)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.eventPanel = QtWidgets.QWidget(self.splitter)
        self.eventPanel.setObjectName("eventPanel")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.eventPanel)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.eventPanel)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 38))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonRecord = QtWidgets.QPushButton(self.frame)
        self.buttonRecord.setMinimumSize(QtCore.QSize(96, 0))
        self.buttonRecord.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/controls/ui/icons/record.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/controls/ui/icons/record.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/controls/ui/icons/record.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.buttonRecord.setIcon(icon1)
        self.buttonRecord.setIconSize(QtCore.QSize(32, 32))
        self.buttonRecord.setCheckable(True)
        self.buttonRecord.setObjectName("buttonRecord")
        self.horizontalLayout.addWidget(self.buttonRecord)
        self.buttonStop = QtWidgets.QPushButton(self.frame)
        self.buttonStop.setEnabled(False)
        self.buttonStop.setMinimumSize(QtCore.QSize(96, 0))
        self.buttonStop.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/controls/ui/icons/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonStop.setIcon(icon2)
        self.buttonStop.setIconSize(QtCore.QSize(32, 32))
        self.buttonStop.setObjectName("buttonStop")
        self.horizontalLayout.addWidget(self.buttonStop)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.buttonPlay = QtWidgets.QPushButton(self.frame)
        self.buttonPlay.setMinimumSize(QtCore.QSize(96, 0))
        self.buttonPlay.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/controls/ui/icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonPlay.setIcon(icon3)
        self.buttonPlay.setIconSize(QtCore.QSize(32, 32))
        self.buttonPlay.setObjectName("buttonPlay")
        self.horizontalLayout.addWidget(self.buttonPlay)
        self.buttonSave = QtWidgets.QPushButton(self.frame)
        self.buttonSave.setMinimumSize(QtCore.QSize(96, 0))
        self.buttonSave.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/controls/ui/icons/accept.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonSave.setIcon(icon4)
        self.buttonSave.setIconSize(QtCore.QSize(32, 32))
        self.buttonSave.setObjectName("buttonSave")
        self.horizontalLayout.addWidget(self.buttonSave)
        self.buttonClear = QtWidgets.QPushButton(self.frame)
        self.buttonClear.setMinimumSize(QtCore.QSize(96, 0))
        self.buttonClear.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/controls/ui/icons/remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonClear.setIcon(icon5)
        self.buttonClear.setIconSize(QtCore.QSize(32, 32))
        self.buttonClear.setObjectName("buttonClear")
        self.horizontalLayout.addWidget(self.buttonClear)
        self.verticalLayout_3.addWidget(self.frame)
        self.eventSplitter = QtWidgets.QSplitter(self.eventPanel)
        self.eventSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.eventSplitter.setHandleWidth(6)
        self.eventSplitter.setObjectName("eventSplitter")
        self.tableEvents = QtWidgets.QTableView(self.eventSplitter)
        self.tableEvents.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableEvents.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableEvents.setObjectName("tableEvents")
        self.tableEvents.horizontalHeader().setDefaultSectionSize(128)
        self.tableEvents.horizontalHeader().setStretchLastSection(True)
        self.tableEvents.verticalHeader().setDefaultSectionSize(20)
        self.layoutWidget = QtWidgets.QWidget(self.eventSplitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableProperties = QtWidgets.QTableView(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tableProperties.sizePolicy().hasHeightForWidth())
        self.tableProperties.setSizePolicy(sizePolicy)
        self.tableProperties.setMinimumSize(QtCore.QSize(198, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableProperties.setFont(font)
        self.tableProperties.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tableProperties.setAlternatingRowColors(True)
        self.tableProperties.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableProperties.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableProperties.setObjectName("tableProperties")
        self.tableProperties.horizontalHeader().setDefaultSectionSize(80)
        self.tableProperties.horizontalHeader().setStretchLastSection(True)
        self.tableProperties.verticalHeader().setVisible(False)
        self.tableProperties.verticalHeader().setDefaultSectionSize(18)
        self.verticalLayout_2.addWidget(self.tableProperties)
        self.eventMgmtButtons = EventMgmtButtons(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventMgmtButtons.sizePolicy().hasHeightForWidth())
        self.eventMgmtButtons.setSizePolicy(sizePolicy)
        self.eventMgmtButtons.setMinimumSize(QtCore.QSize(0, 32))
        self.eventMgmtButtons.setMaximumSize(QtCore.QSize(16777215, 32))
        self.eventMgmtButtons.setObjectName("eventMgmtButtons")
        self.verticalLayout_2.addWidget(self.eventMgmtButtons)
        self.verticalLayout_3.addWidget(self.eventSplitter)
        self.snapshotPanel = QtWidgets.QWidget(self.splitter)
        self.snapshotPanel.setObjectName("snapshotPanel")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.snapshotPanel)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget = QtWidgets.QWidget(self.snapshotPanel)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 38))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.buttonCapture = QtWidgets.QPushButton(self.widget)
        self.buttonCapture.setMinimumSize(QtCore.QSize(150, 0))
        self.buttonCapture.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/controls/ui/icons/image_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonCapture.setIcon(icon6)
        self.buttonCapture.setIconSize(QtCore.QSize(32, 32))
        self.buttonCapture.setObjectName("buttonCapture")
        self.horizontalLayout_3.addWidget(self.buttonCapture)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.buttonPlaySnaps = QtWidgets.QPushButton(self.widget)
        self.buttonPlaySnaps.setMinimumSize(QtCore.QSize(150, 0))
        self.buttonPlaySnaps.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/controls/ui/icons/image_next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonPlaySnaps.setIcon(icon7)
        self.buttonPlaySnaps.setIconSize(QtCore.QSize(32, 32))
        self.buttonPlaySnaps.setObjectName("buttonPlaySnaps")
        self.horizontalLayout_3.addWidget(self.buttonPlaySnaps)
        self.buttonDiff = QtWidgets.QPushButton(self.widget)
        self.buttonDiff.setMinimumSize(QtCore.QSize(96, 0))
        self.buttonDiff.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/controls/ui/icons/page_swap.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonDiff.setIcon(icon8)
        self.buttonDiff.setIconSize(QtCore.QSize(32, 32))
        self.buttonDiff.setObjectName("buttonDiff")
        self.horizontalLayout_3.addWidget(self.buttonDiff)
        self.buttonOCR = QtWidgets.QPushButton(self.widget)
        self.buttonOCR.setMinimumSize(QtCore.QSize(96, 0))
        self.buttonOCR.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/controls/ui/icons/image_edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonOCR.setIcon(icon9)
        self.buttonOCR.setIconSize(QtCore.QSize(32, 32))
        self.buttonOCR.setObjectName("buttonOCR")
        self.horizontalLayout_3.addWidget(self.buttonOCR)
        self.verticalLayout_5.addWidget(self.widget)
        self.snapshotSplitter = QtWidgets.QSplitter(self.snapshotPanel)
        self.snapshotSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.snapshotSplitter.setHandleWidth(6)
        self.snapshotSplitter.setObjectName("snapshotSplitter")
        self.listSnap = QtWidgets.QListView(self.snapshotSplitter)
        self.listSnap.setObjectName("listSnap")
        self.layoutWidget1 = QtWidgets.QWidget(self.snapshotSplitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelPreview = AspectRatioPixmapLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPreview.sizePolicy().hasHeightForWidth())
        self.labelPreview.setSizePolicy(sizePolicy)
        self.labelPreview.setMinimumSize(QtCore.QSize(198, 150))
        self.labelPreview.setMaximumSize(QtCore.QSize(16777215, 150))
        self.labelPreview.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelPreview.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelPreview.setText("")
        self.labelPreview.setPixmap(QtGui.QPixmap(":/eyecandy/ui/icons/snitch_a30.png"))
        self.labelPreview.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPreview.setObjectName("labelPreview")
        self.verticalLayout_4.addWidget(self.labelPreview)
        self.tableSnapProps = QtWidgets.QTableView(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tableSnapProps.sizePolicy().hasHeightForWidth())
        self.tableSnapProps.setSizePolicy(sizePolicy)
        self.tableSnapProps.setMinimumSize(QtCore.QSize(198, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableSnapProps.setFont(font)
        self.tableSnapProps.setAlternatingRowColors(True)
        self.tableSnapProps.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableSnapProps.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableSnapProps.setObjectName("tableSnapProps")
        self.tableSnapProps.horizontalHeader().setDefaultSectionSize(80)
        self.tableSnapProps.horizontalHeader().setStretchLastSection(True)
        self.tableSnapProps.verticalHeader().setVisible(False)
        self.tableSnapProps.verticalHeader().setDefaultSectionSize(18)
        self.verticalLayout_4.addWidget(self.tableSnapProps)
        self.capsEventMgmtButtons = EventMgmtButtons(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.capsEventMgmtButtons.sizePolicy().hasHeightForWidth())
        self.capsEventMgmtButtons.setSizePolicy(sizePolicy)
        self.capsEventMgmtButtons.setMinimumSize(QtCore.QSize(0, 32))
        self.capsEventMgmtButtons.setMaximumSize(QtCore.QSize(16777215, 32))
        self.capsEventMgmtButtons.setObjectName("capsEventMgmtButtons")
        self.verticalLayout_4.addWidget(self.capsEventMgmtButtons)
        self.verticalLayout_5.addWidget(self.snapshotSplitter)
        self.verticalLayout.addWidget(self.splitter)
        Controller.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Controller)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOpenRecent = QtWidgets.QMenu(self.menuFile)
        self.menuOpenRecent.setObjectName("menuOpenRecent")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        Controller.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Controller)
        self.statusbar.setObjectName("statusbar")
        Controller.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(Controller)
        self.actionAbout.setObjectName("actionAbout")
        self.actionQuit = QtWidgets.QAction(Controller)
        self.actionQuit.setObjectName("actionQuit")
        self.actionRecord = QtWidgets.QAction(Controller)
        self.actionRecord.setCheckable(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/record.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRecord.setIcon(icon10)
        self.actionRecord.setObjectName("actionRecord")
        self.actionPause = QtWidgets.QAction(Controller)
        self.actionPause.setCheckable(True)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/icons/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPause.setIcon(icon11)
        self.actionPause.setObjectName("actionPause")
        self.actionStop = QtWidgets.QAction(Controller)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/icons/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon12)
        self.actionStop.setObjectName("actionStop")
        self.actionSave = QtWidgets.QAction(Controller)
        self.actionSave.setObjectName("actionSave")
        self.actionOpen = QtWidgets.QAction(Controller)
        self.actionOpen.setObjectName("actionOpen")
        self.actionMinimizeWhenRecording = QtWidgets.QAction(Controller)
        self.actionMinimizeWhenRecording.setCheckable(True)
        self.actionMinimizeWhenRecording.setObjectName("actionMinimizeWhenRecording")
        self.actionSettings = QtWidgets.QAction(Controller)
        self.actionSettings.setObjectName("actionSettings")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.menuOpenRecent.menuAction())
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuOptions.addAction(self.actionSettings)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Controller)
        self.buttonRecord.clicked['bool'].connect(self.buttonStop.setEnabled)
        self.buttonStop.clicked['bool'].connect(self.buttonRecord.setChecked)
        self.buttonStop.clicked['bool'].connect(self.buttonStop.setEnabled)
        self.buttonRecord.clicked['bool'].connect(self.buttonRecord.setDisabled)
        self.buttonStop.clicked['bool'].connect(self.buttonRecord.setDisabled)
        self.actionQuit.triggered.connect(Controller.close)
        self.actionAbout.triggered.connect(Controller.show_about_dialog)
        self.buttonSave.clicked.connect(self.actionSave.trigger)
        self.actionSave.triggered.connect(Controller.show_save_dialog)
        self.buttonRecord.clicked.connect(Controller.update_status_label)
        self.actionOpen.triggered.connect(Controller.show_open_dialog)
        self.actionSettings.triggered.connect(Controller.show_settings_dialog)
        self.menuOpenRecent.triggered['QAction*'].connect(Controller.open_recent)
        QtCore.QMetaObject.connectSlotsByName(Controller)

    def retranslateUi(self, Controller):
        _translate = QtCore.QCoreApplication.translate
        self.buttonRecord.setText(_translate("Controller", "Record"))
        self.buttonStop.setText(_translate("Controller", "Stop"))
        self.buttonPlay.setText(_translate("Controller", "Play"))
        self.buttonSave.setText(_translate("Controller", "Save…"))
        self.buttonClear.setText(_translate("Controller", "Clear"))
        self.buttonCapture.setText(_translate("Controller", "Add screenshot"))
        self.buttonPlaySnaps.setText(_translate("Controller", "Play screenshots"))
        self.buttonDiff.setText(_translate("Controller", "Diff"))
        self.buttonOCR.setText(_translate("Controller", "OCR"))
        self.menuFile.setTitle(_translate("Controller", "File"))
        self.menuOpenRecent.setTitle(_translate("Controller", "Open recent"))
        self.menuHelp.setTitle(_translate("Controller", "Help"))
        self.menuOptions.setTitle(_translate("Controller", "Options"))
        self.actionAbout.setText(_translate("Controller", "About…"))
        self.actionQuit.setText(_translate("Controller", "&Quit"))
        self.actionRecord.setText(_translate("Controller", "Record"))
        self.actionPause.setText(_translate("Controller", "Pause"))
        self.actionStop.setText(_translate("Controller", "Stop"))
        self.actionSave.setText(_translate("Controller", "Save…"))
        self.actionOpen.setText(_translate("Controller", "Open…"))
        self.actionMinimizeWhenRecording.setText(_translate("Controller", "Minimize when recording"))
        self.actionSettings.setText(_translate("Controller", "Settings…"))
from snitch.ui.aspect_ratio_pixmap_label import AspectRatioPixmapLabel
from snitch.ui.list_manager import EventMgmtButtons
from snitch import assets_rc
