sudo: false
language: python
dist: xenial
python:
  - "2.7"
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install -r requirements_tests.txt

script:
  - python -m pytest --cov=numerapi

after_success:
  - codecov
