[tool.poetry]
name = "picklejar3"
version = "0.2.0"
description = "A library to store data"
authors = ["walchko <walchko@users.noreply.github.com>"]
readme = "readme.md"
license = "MIT"
homepage = "https://pypi.org/project/picklejar3/"
repository = 'https://github.com/MomsFriendlyRobotCompany/picklejar3'
# documentation = "http://..."
keywords = ['library', 'robotics', 'sensor', 'data', 'picklejar']
classifiers = [
    'Development Status :: 4 - Beta',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: MIT License',
    'Operating System :: OS Independent',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Topic :: Software Development :: Libraries',
    'Topic :: Software Development :: Libraries :: Python Modules',
    'Topic :: Software Development :: Libraries :: Application Frameworks'
]

# [tool.poetry.scripts]
# # script_name = 'myscript:main'

[tool.poetry.dependencies]
python = ">=3.6"
# colorama = "*"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
# mypy = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
