# path to package source code relative to package root
package_source_path: cavcalc

# path to package documentation source relative to package root
docs_source_path: docs/source

# files and patterns to exclude from documenting
exclude:
    files: ['^_', '^\.', 'version', 'test', 'constants', 'handler', 'parsing', 'plotting', 'units']
    subpkgs: ['^_', '^\.', 'version', 'test', 'utilities']

    classes: []
    enums: []
    dataclasses: []
    methods: []
    functions: []
