
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-06T12:21:52-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "0dde0ccc732e897da2f734f472893eb453916d3f",
 "version": "2.2.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
