dist: bionic
sudo: false
language: python
python: 3.8
cache:
  directories:
    - ./tests/artifacts

install:
  - pip install . --progress-bar off
  - pip install codecov
  - pip install pytest

script:
  - coverage run -m pytest

# Push the results to codecov
after_success:
  - codecov
