
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-12T03:45:32+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9f0c01e29429c0f6f18c6f44c3677e578c450096",
 "version": "0.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
