site_name: apidaora
site_description: Asgi App using typing annotation

theme:
    name: 'material'
    custom_dir: 'theme'
    palette:
      primary: 'pink'
      accent: 'grey'
    logo: 'apidaora-white.svg'
    favicon: 'favicon.png'

repo_name: dutradda/apidaora
repo_url: https://github.com/dutradda/apidaora
edit_uri: ''

nav:
    - apidaora: index.md
    # - Features: features.md
    - Python dataclass intro: python-dataclass.md
    - JSON intro: json.md
    # - Http intro: http.md
    - Core Module: using-asgi-module.md
    - Class Controllers: using-class-controller.md
    - Middlewares: using-middlewares.md
    - Default Options: using-options.md
    - Background Tasks: using-background-task-controller.md
    - Async Background Tasks: using-async-background-task-controller.md
    - Async Background Task with Redis: using-redis-background-task-async-controller.md
    - Background Task with Redis: using-redis-background-task-controller.md
    - Background Task with Lock: using-background-task-lock-controller.md
    - Background Task with Lock by Args: using-background-task-lock-args-controller.md
    - Background Task with Lock by Args and Redis: using-redis-background-task-lock-args-controller.md
    - Upload gzip files: using-gzip-request-body.md
    - Prevent Request Middleware: using-prevent-request-middleware.md
    # - Complete Request/Response: tutorial/01-complete-request-response.md
    # - Deserializations bad requests: tutorial/02-deserializations-bad-requests.md
    # - Validating fields: tutorial/03-validating-fields.md
    # - Complex nested structures: tutorial/04-complex-nested-structures.md
    # - Alternatives, Inspiration and Comparisons: alternatives.md
    # - Benchmarks: benchmarks.md
    # - Help apidaora - Get Help: help.md
    - Development - Contributing: contributing.md
    - Changelog: changelog.md

markdown_extensions:
    - markdown_include.include:
        base_path: docs
    - codehilite:
        guess_lang: false

extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css
