[build-system]
requires = [
    "setuptools",
    "wheel",
]
build-backend = "setuptools.build_meta:__legacy__"

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = python3.7
isolated_build = true

[testenv]
basepython = python3.7
deps =
    flake8
    pytest
    requests
commands =
    flake8 . --extend-ignore=E501
    pytest tests

[testenv:build-dist]
usedevelop = false
skip_install = true
deps =
    pep517 >= 0.8.2
    twine >= 3.1.1
commands =
    rm -rfv {toxinidir}/dist/
    python -m pep517.check {toxinidir}
    python -m pep517.build \
      --source \
      --binary \
      --out-dir {toxinidir}/dist \
      {toxinidir}
    twine check dist/*

[flake8]
exclude = .tox,*.egg,build,data
select = E,W,F
max-line-length = 120
"""
