# Based on http://conda.pydata.org/docs/travis.html
language: minimal
sudo: false # use container based build
notifications:
  email: false

matrix:
  fast_finish: true
  include:
  - env: CONDA_ENV=py36
  - env: CONDA_ENV=py37
  - env: CONDA_ENV=py37-upstream_master
  - env: CONDA_ENV=py38
  allow_failures:
  - env: CONDA_ENV=py38

before_install:
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - conda info -a

install:
  - conda env create --file ci/environment-$CONDA_ENV.yml
  - source activate test_env_xarrayutils
  - conda list
  - pip install --no-deps -e .

script:
  - py.test xarrayutils --cov=xarrayutils --cov-config .coveragerc --cov-report term-missing

after_success:
  - codecov
