
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-04T12:11:41-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "d9c9939989c1f88a7c0311ff9f66230a087242d8",
 "version": "0.8.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
