[tool.poetry]
name = "a-la-mode"
version = "0.1.2"
description = "A tool for describing pure data pipelines that enables avoiding repeating work (incrementality) and keeping old data around (provenance)"
authors = ["thattommyhall <thattommyhall@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
"bencode.py" = "^2.1.0"
toolz = "^0.10.0"
toposort = "1.5"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
pytest-watch = "^4.2.0"
colorama = "^0.4.3"
deepdiff = "^4.2.0"
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

