
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "cd64d83b47246ca81c22cb8656eedc1d9eeab80c",
 "version": "0.17.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
