
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-13T15:56:14-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "b26a74437c92d4a671727bdb311b6b7115dcd3e2",
 "version": "4.14.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
