
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-13T14:22:45-1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7c8601a08990dd21b418719a5e1543c5951e2a14",
 "version": "v0.2.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
