#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

install_requires = \
['astcheck>=0.2.3']

entry_points = \
{'console_scripts': ['astsearch = astsearch:main']}

setup(name='astsearch',
      version='0.2.0',
      description='Intelligently search Python source code',
      author='Thomas Kluyver',
      author_email='thomas@kluyver.me.uk',
      url='https://github.com/takluyver/astsearch',
      py_modules=['astsearch'],
      install_requires=install_requires,
      entry_points=entry_points,
      python_requires='>=3',
     )
