# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from spaceone.api.core.v1 import handler_pb2 as spaceone_dot_api_dot_core_dot_v1_dot_handler__pb2
from spaceone.api.identity.v1 import domain_pb2 as spaceone_dot_api_dot_identity_dot_v1_dot_domain__pb2


class DomainStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.create = channel.unary_unary(
        '/spaceone.api.identity.v1.Domain/create',
        request_serializer=spaceone_dot_api_dot_identity_dot_v1_dot_domain__pb2.CreateDomainRequest.SerializeToString,
        response_deserializer=spaceone_dot_api_dot_identity_dot_v1_dot_domain__pb2.DomainInfo.FromString,
        )
    self.update = channel.unary_unary(
        '/spaceone.api.identity.v1.Domain/update',
        request_serializer=spaceone_dot_api_dot_identity_dot_v1_dot_domain__pb2.UpdateDomainRequest.SerializeToString,
        response_deserializer=spaceone_dot_api_dot_identity_dot_v1_dot_domain__pb2.DomainInfo.FromString,
        )
    self.delete = channel.unary_unary(
        '/spaceone.api.identity.v1.Domain/delete',
        request_serializer=spaceone_dot_api_dot_identity_dot_v1_dot_domain__pb2.DomainRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.enable = channel.unary_unary(
        '/spaceone.api.identity.v1.Domain/enable',
        request_serializer=spaceone_dot_api_dot_identity_dot_v1_dot_domain__pb2.DomainRequest.SerializeToString,
        response_deserializer=spaceone_dot_api_dot_identity_dot_v1_dot_domain__pb2.DomainInfo.FromString,
        )
    self.disable = channel.unary_unary(
        '/spaceone.api.identity.v1.Domain/disable',
        request_serializer=spaceone_dot_api_dot_identity_dot_v1_dot_domain__pb2.DomainRequest.SerializeToString,
        response_deserializer=spaceone_dot_api_dot_identity_dot_v1_dot_domain__pb2.DomainInfo.FromString,
        )
    self.get = channel.unary_unary(
        '/spaceone.api.identity.v1.Domain/get',
        request_serializer=spaceone_dot_api_dot_identity_dot_v1_dot_domain__pb2.DomainRequest.SerializeToString,
        response_deserializer=spaceone_dot_api_dot_identity_dot_v1_dot_domain__pb2.DomainInfo.FromString,
        )
    self.list = channel.unary_unary(
        '/spaceone.api.identity.v1.Domain/list',
        request_serializer=spaceone_dot_api_dot_identity_dot_v1_dot_domain__pb2.DomainQuery.SerializeToString,
        response_deserializer=spaceone_dot_api_dot_identity_dot_v1_dot_domain__pb2.DomainsInfo.FromString,
        )
    self.get_public_key = channel.unary_unary(
        '/spaceone.api.identity.v1.Domain/get_public_key',
        request_serializer=spaceone_dot_api_dot_core_dot_v1_dot_handler__pb2.AuthenticationRequest.SerializeToString,
        response_deserializer=spaceone_dot_api_dot_core_dot_v1_dot_handler__pb2.AuthenticationResponse.FromString,
        )
    self.get_domain_key = channel.unary_unary(
        '/spaceone.api.identity.v1.Domain/get_domain_key',
        request_serializer=spaceone_dot_api_dot_core_dot_v1_dot_handler__pb2.AuthenticationRequest.SerializeToString,
        response_deserializer=spaceone_dot_api_dot_identity_dot_v1_dot_domain__pb2.DomainKeyResponse.FromString,
        )


class DomainServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def create(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def update(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def enable(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def disable(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def list(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get_public_key(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get_domain_key(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DomainServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'create': grpc.unary_unary_rpc_method_handler(
          servicer.create,
          request_deserializer=spaceone_dot_api_dot_identity_dot_v1_dot_domain__pb2.CreateDomainRequest.FromString,
          response_serializer=spaceone_dot_api_dot_identity_dot_v1_dot_domain__pb2.DomainInfo.SerializeToString,
      ),
      'update': grpc.unary_unary_rpc_method_handler(
          servicer.update,
          request_deserializer=spaceone_dot_api_dot_identity_dot_v1_dot_domain__pb2.UpdateDomainRequest.FromString,
          response_serializer=spaceone_dot_api_dot_identity_dot_v1_dot_domain__pb2.DomainInfo.SerializeToString,
      ),
      'delete': grpc.unary_unary_rpc_method_handler(
          servicer.delete,
          request_deserializer=spaceone_dot_api_dot_identity_dot_v1_dot_domain__pb2.DomainRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'enable': grpc.unary_unary_rpc_method_handler(
          servicer.enable,
          request_deserializer=spaceone_dot_api_dot_identity_dot_v1_dot_domain__pb2.DomainRequest.FromString,
          response_serializer=spaceone_dot_api_dot_identity_dot_v1_dot_domain__pb2.DomainInfo.SerializeToString,
      ),
      'disable': grpc.unary_unary_rpc_method_handler(
          servicer.disable,
          request_deserializer=spaceone_dot_api_dot_identity_dot_v1_dot_domain__pb2.DomainRequest.FromString,
          response_serializer=spaceone_dot_api_dot_identity_dot_v1_dot_domain__pb2.DomainInfo.SerializeToString,
      ),
      'get': grpc.unary_unary_rpc_method_handler(
          servicer.get,
          request_deserializer=spaceone_dot_api_dot_identity_dot_v1_dot_domain__pb2.DomainRequest.FromString,
          response_serializer=spaceone_dot_api_dot_identity_dot_v1_dot_domain__pb2.DomainInfo.SerializeToString,
      ),
      'list': grpc.unary_unary_rpc_method_handler(
          servicer.list,
          request_deserializer=spaceone_dot_api_dot_identity_dot_v1_dot_domain__pb2.DomainQuery.FromString,
          response_serializer=spaceone_dot_api_dot_identity_dot_v1_dot_domain__pb2.DomainsInfo.SerializeToString,
      ),
      'get_public_key': grpc.unary_unary_rpc_method_handler(
          servicer.get_public_key,
          request_deserializer=spaceone_dot_api_dot_core_dot_v1_dot_handler__pb2.AuthenticationRequest.FromString,
          response_serializer=spaceone_dot_api_dot_core_dot_v1_dot_handler__pb2.AuthenticationResponse.SerializeToString,
      ),
      'get_domain_key': grpc.unary_unary_rpc_method_handler(
          servicer.get_domain_key,
          request_deserializer=spaceone_dot_api_dot_core_dot_v1_dot_handler__pb2.AuthenticationRequest.FromString,
          response_serializer=spaceone_dot_api_dot_identity_dot_v1_dot_domain__pb2.DomainKeyResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'spaceone.api.identity.v1.Domain', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
