
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-06T10:26:54+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "529c875305b707d4d65d5fa7bca79bdead88fcb0",
 "version": "1.4.0.post.dev103"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
