[tool.poetry]
name = "CloudMage-GitUtils"
version = "1.0.0"
description = "Git based helpers and Report Templates"
authors = ["Rich Nason <rnason@cloudmage.io>"]
maintainers = ["Rich Nason <rnason@cloudmage.io>"]
license = "GPL-3.0-or-later"
readme = "README.md"
include = [
    "CHANGELOG.md",
    "LICENSE"
]
homepage = "https://github.com/CloudMages/PyPkgs-GitUtils"
repository = "https://github.com/CloudMages/PyPkgs-GitUtils"
documentation = "https://github.com/CloudMages/PyPkgs-GitUtils"
keywords = [
    "Packages",
    "CloudMage",
    "Git"
]

classifiers = [
    "Environment :: Console",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Documentation",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

packages = [
    {include = "cloudmage"}
]

[tool.poetry.urls]
"Releases" = "https://github.com/CloudMages/PyPkgs-GitUtils/releases"
"Issues" = "https://github.com/CloudMages/PyPkgs-GitUtils/issues"

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.22.0"
PyGithub = "^1.47"
progress = "^1.5"
cloudmage-jinjautils = "^1.0.5"

[tool.poetry.dev-dependencies]
pytest = "^4.6"
pylint = "^2.4.4"
coverage = "^5.0.3"

[tool.poetry.scripts]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
