
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-12T16:30:53-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "845bea550447991b194ef884713a7b3be4b4a6c2",
 "version": "20.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
