COLUMN_MANY = 'MANY'
COLUMN_ONE = 'ONE'

SERIES_TYPE_CONTINUOUS = 'CONTINUOUS'
SERIES_TYPE_DISCRETE = 'DISCRETE'
SERIES_TYPE_BOOLEAN = 'BOOLEAN'
SERIES_TYPE_DATETIME = 'DATETIME'

STORAGE_TYPE_SQLITE = 'SQLITE'
STORAGE_TYPE_MSSQL = 'MSSQL'
STORAGE_TYPE_FILES = 'FILES'

ROLE_PARENT = 'PARENT'
ROLE_CHILD = 'CHILD'
ROLE_SIBLING = 'SIBLING'
ROLE_STEP_SIBLING = 'STEP_SIBLING'

FILTER_TYPE_RANGE = 'RANGE'
FILTER_TYPE_SELECTION = 'SELECTION'

AGGREGATE_FXN_COUNT = 'COUNT'
AGGREGATE_FXN_PERCENT = 'PERCENT'
AGGREGATE_FXN_SUM = 'SUM'
AGGREGATE_FXN_MEAN = 'MEAN'
AGGREGATE_FXN_MEDIAN = 'MEDIAN'

DEFAULT_METADATA_NAME = 'metadata.db'
DEFAULT_DATADB_NAME = 'db_extract_data.db'
