
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-10T09:27:25-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "cab48c6e6d00a9657ecead40f65c45843c7a6e31",
 "version": "0.9.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
