# coding: utf-8

"""
    Agilicus API

    Agilicus API endpoints  # noqa: E501

    The version of the OpenAPI document: 2020.04.06
    Contact: dev@agilicus.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import agilicus_api
from agilicus_api.models.group_member_data import GroupMemberData  # noqa: E501
from agilicus_api.rest import ApiException

class TestGroupMemberData(unittest.TestCase):
    """GroupMemberData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GroupMemberData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = agilicus_api.models.group_member_data.GroupMemberData()  # noqa: E501
        if include_optional :
            return GroupMemberData(
                member_id = '123'
            )
        else :
            return GroupMemberData(
        )

    def testGroupMemberData(self):
        """Test GroupMemberData"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
