environment:
  matrix:
    - COV_FAIL_UNDER: 70
install:
  - pip install tox codecov
build: false
test_script:
  - tox -e py37,py38 -- -vv tests/test_github.py tests/test_bitbucket.py tests/test_gitlab.py tests/test_pagure.py tests/test_db.py tests/test_caching.py tests/test_fedora.py tests/test_stdlib.py
  - codecov
skip_branch_with_pr: true
