clone_depth: 50

max_jobs: 100

cache:
  - '%LOCALAPPDATA%\pip\Cache'


environment:
  matrix:
    - PYTHON: C:\Python37
      PYTHON_VERSION: 3.7
      PYTHON_ARCH: 32

    - PYTHON: C:\Python37-x64
      PYTHON_VERSION: 3.7
      PYTHON_ARCH: 64

    - PYTHON: C:\Python36
      PYTHON_VERSION: 3.6
      PYTHON_ARCH: 32

    - PYTHON: C:\Python36-x64
      PYTHON_VERSION: 3.6
      PYTHON_ARCH: 64

    - PYTHON: C:\Python35
      PYTHON_VERSION: 3.5
      PYTHON_ARCH: 32

    - PYTHON: C:\Python35-x64
      PYTHON_VERSION: 3.5
      PYTHON_ARCH: 64

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
  - "ECHO \"%APPVEYOR_SCHEDULED_BUILD%\""
install:
  # Get needed submodules
  - git submodule update --init

  # Prepend required Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

  # Check that we have the expected version and architecture for Python
  - python --version
  - >-
     python -c "import sys,platform,struct;
     print(sys.platform, platform.machine(), struct.calcsize('P') * 8, )"

  # Upgrade to the latest pip, setuptools, and wheel.
  - python -m pip install -U pip setuptools wheel

  # Install build requirements.
  - pip install -r requirements.txt

build_script:
  - pip wheel . -w wheels

test_script:
  - pip install littlefs-python --no-index -f wheels/
  - pytest test

artifacts:
  - path: 'wheels\*.whl'
    name: Wheels


deploy:
  provider: GitHub
  auth_token:
    secure: YeRSRl2x/C/eqvVKd34AWqi3CTRnP1ZSBNEaeSuQTFJk/VWlwckEp3zoof6lpEXk
  artifact: Wheels
  on:
    APPVEYOR_REPO_TAG: true

