[tool.poetry]
name = "django-command-overrides"
version = "0.1.0"
description = ""
authors = ["Jonathan Meier <jonathanwmeier@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
django = ">=2.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pre-commit = "^2.2.0"
pytest-django = "^3.8.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
