# coding: utf-8

"""
    Agilicus API

    Agilicus API endpoints  # noqa: E501

    The version of the OpenAPI document: 2020.04.06
    Contact: dev@agilicus.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import agilicus_api
from agilicus_api.api.view_audit_records_api import ViewAuditRecordsApi  # noqa: E501
from agilicus_api.rest import ApiException


class TestViewAuditRecordsApi(unittest.TestCase):
    """ViewAuditRecordsApi unit test stubs"""

    def setUp(self):
        self.api = agilicus_api.api.view_audit_records_api.ViewAuditRecordsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_audits_audit_query(self):
        """Test case for audits_audit_query

        View audit records  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
