[tool.poetry]
name = "investify"
version = "0.0.1"
description = "Get automated price alert based on investing.com prices"
authors = ["Abhishek Guha <abhi.workspace@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.1.1"
requests = "^2.23.0"
twilio = "^6.38.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
