
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-02T23:22:33-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "5d9efb4e89c3b155b7ac3ce82bc6d258377c1a5f",
 "version": "0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
