order = [
    'tpDcc.libs.qt.widgets.layouts',
    'tpDcc.libs.qt.widgets.graphicseffects',
    'tpDcc.libs.qt.widgets.buttons',
    'tpDcc.libs.qt.widgets.label',
    'tpDcc.libs.qt.widgets.lineedit',
    'tpDcc.libs.qt.widgets.splitters',
    'tpDcc.libs.qt.widgets.gif',
    'tpDcc.libs.qt.widgets.directory',
    'tpDcc.libs.qt.widgets.grid',
    'tpDcc.libs.qt.widgets.search',
    'tpDcc.libs.qt.widgets.treewidgets',
    'tpDcc.libs.qt.widgets.history',
    'tpDcc.libs.qt.widgets.tabbars',
    'tpDcc.libs.qt.widgets.tabs',
    'tpDcc.libs.qt.widgets.overlay',
    'tpDcc.libs.qt.widgets.dpi',
    'tpDcc.libs.qt.widgets.stack'
]
