name: test_env_cmip6_preprocessing
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pyproj
  - matplotlib
  - intake
  - cartopy
  - gcsfs # needed for google cloud storage
  - zarr # needed for google cloud storage tests
  - codecov
  - pytest-cov
  - black
  - pip:
    - git+https://github.com/mathause/regionmask.git
    - git+https://github.com/pydata/xarray.git
    - git+https://github.com/numpy/numpy.git
    - git+https://github.com/pandas-dev/pandas.git
    - git+https://github.com/NCAR/intake-esm.git
    - git+https://github.com/xgcm/xgcm.git
