
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-05T10:37:04-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a966cd9ae415202f947982516cd40a81d1e96648",
 "version": "5.0b8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
