
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-13T11:44:32+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d826c9cda5183cb51c81cbde098b0f920ea252a5",
 "version": "1.6.0.post.dev13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
